#!/usr/bin/env node
// Generates pwabuilder-sw.js with auto-discovered assets and content-based cache hash.
// Run: node generate-sw.js
// Run this before every deploy so new/changed assets are picked up automatically.

import { createHash } from 'crypto';
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'fs';
import { join, relative, extname } from 'path';

const ROOT = new URL('.', import.meta.url).pathname;

// Asset directories and individual files to scan
const ASSET_DIRS = ['assets', 'scripts'];
const ROOT_FILES = ['index.html', 'offline.html', 'manifest.json', 'game-main.js'];
const ALLOWED_EXTENSIONS = new Set([
  '.html', '.js', '.mjs', '.css', '.json',
  '.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp',
  '.mp3', '.ogg', '.wav', '.webm',
  '.woff', '.woff2', '.ttf', '.otf',
]);

// Directories to skip
const SKIP_DIRS = new Set(['node_modules', '.git', '.claude', '.playwright-mcp', '.npm-cache', 'windows11', 'android', 'ios', 'dist']);

function walkDir(dir) {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      if (!SKIP_DIRS.has(entry)) {
        results.push(...walkDir(fullPath));
      }
    } else if (ALLOWED_EXTENSIONS.has(extname(entry).toLowerCase())) {
      results.push(fullPath);
    }
  }
  return results;
}

// Discover all cacheable assets
const assets = new Set();

// Add root files
for (const file of ROOT_FILES) {
  const fullPath = join(ROOT, file);
  if (existsSync(fullPath)) {
    assets.add('/' + file);
  }
}

// Add '/' for the root route
assets.add('/');

// Walk asset directories
for (const dir of ASSET_DIRS) {
  const dirPath = join(ROOT, dir);
  if (!existsSync(dirPath)) continue;
  for (const filePath of walkDir(dirPath)) {
    const rel = relative(ROOT, filePath);
    assets.add('/' + rel);
  }
}

// Critical CDN dependencies that must be pre-cached for offline play
// Extracted from game-main.js imports
const CDN_DEPS = [
  'https://unpkg.com/kaplay@4000.0.0-alpha.5/dist/kaplay.mjs',
];

// Sort for deterministic output
const sortedAssets = [...assets].sort();

// Compute content hash from all asset files for cache busting
const hasher = createHash('md5');
for (const asset of sortedAssets) {
  const filePath = join(ROOT, asset === '/' ? 'index.html' : asset);
  if (existsSync(filePath)) {
    hasher.update(readFileSync(filePath));
  }
}
const contentHash = hasher.digest('hex').slice(0, 8);

// Generate the service worker
const sw = `// Auto-generated by generate-sw.js — do not edit manually
// Cache hash: ${contentHash}
const CACHE_NAME = 'onions-life-${contentHash}';

const PRECACHE_ASSETS = ${JSON.stringify(sortedAssets, null, 2)};

// Critical CDN modules to pre-cache on install (game won't load without these)
const PRECACHE_CDN = ${JSON.stringify(CDN_DEPS, null, 2)};

// CDN origins to cache on first fetch (for non-critical imports like Supabase)
const CACHEABLE_CDN = [
  'https://unpkg.com',
  'https://esm.sh',
];

// --- Install: pre-cache all game assets + critical CDN modules ---
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => {
        // Pre-cache CDN modules with cross-origin fetch
        const cdnPromises = PRECACHE_CDN.map((url) =>
          fetch(url, { mode: 'cors' })
            .then((resp) => cache.put(url, resp))
            .catch((err) => console.warn('Failed to pre-cache CDN:', url, err))
        );
        return Promise.all([cache.addAll(PRECACHE_ASSETS), ...cdnPromises]);
      })
      .then(() => self.skipWaiting())
  );
});

// --- Activate: delete old caches, claim clients immediately ---
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(
        names
          .filter((n) => n.startsWith('onions-life-') && n !== CACHE_NAME)
          .map((n) => caches.delete(n))
      )
    ).then(() => self.clients.claim())
  );
});

// --- Fetch strategies ---
self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Only handle GET
  if (request.method !== 'GET') return;

  // Never cache analytics or remote APIs
  if (url.hostname.includes('google') || url.hostname.includes('gtag')) return;
  if (url.hostname.includes('appwrite') || url.hostname.includes('supabase')) return;

  // HTML navigation: network-first so new deploys are picked up, cache fallback for offline
  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request));
    return;
  }

  // CDN resources (Kaplay engine): stale-while-revalidate
  if (CACHEABLE_CDN.some((origin) => request.url.startsWith(origin))) {
    event.respondWith(staleWhileRevalidate(request));
    return;
  }

  // All other same-origin assets: cache-first (they're pre-cached and versioned)
  if (url.origin === self.location.origin) {
    event.respondWith(cacheFirst(request));
    return;
  }
});

// Network-first: try network, update cache, fall back to cache then offline page
async function networkFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const response = await fetch(request);
    cache.put(request, response.clone());
    return response;
  } catch (e) {
    return (await cache.match(request)) || (await cache.match('/offline.html'));
  }
}

// Cache-first: serve from cache instantly, only hit network if not cached
async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  try {
    const cache = await caches.open(CACHE_NAME);
    const response = await fetch(request);
    cache.put(request, response.clone());
    return response;
  } catch (e) {
    return new Response('Offline', { status: 503 });
  }
}

// Stale-while-revalidate: serve cache immediately, update in background
async function staleWhileRevalidate(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);

  const fetchPromise = fetch(request).then((response) => {
    cache.put(request, response.clone());
    return response;
  }).catch(() => null);

  return cached || (await fetchPromise) || new Response('Offline', { status: 503 });
}
`;

writeFileSync(join(ROOT, 'pwabuilder-sw.js'), sw);
console.log(`Generated pwabuilder-sw.js`);
console.log(`  Cache name: onions-life-${contentHash}`);
console.log(`  Pre-cached assets: ${sortedAssets.length}`);
