 //loadLevels()
const LEVELS = [
  //intro
  [
    '^                                                       =',
    '^                                                       =',
    '^                                                       =',
    '^                                                       =',
    '^                                                       =',
    '^                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=         l }  $$$      G ^      l     $$      }       O=',
    '=========================================================',

  ],
  //Classic
  [
    '	=                      ',
    '       ^^               ',
    '=                                                          ^^                ',
    '=                                                      ^^^^^^^^              ',
    '=                                                                            ',
    '=                               l$                                        ',
    '=                              ==      !                   =                  ',
    '=                            $                             =         ',
    '=                         ==  ^^                          ==          -',
    '=                    l $                                  ==$         =     l$ ',
    '=              $    ===  ^                      $      =  = =              ===',
    '=     $     } l                                       ==ll=        l    $    ',
    '=  l  ^    === ^^^   ^^^^^^^^^^^^^^^       ^      ^  =     = $   O=^^^^ =    ',
    '=====================================================================.        ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
    '','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',
    '                                                        QQQQ'
  ],
  //Flying for Coins
  [
    "=                          ",
    "=         ^    ^           ",
    "=                          ",
    "=                          ",
    "=    $    $    $    $     $",
    "=    $    $    $    $     $",
    "=                          ",
    "=         l                ",
    "=                l         ",
    "=                          ",
    "=                          ",
    "=     }      ^       l   O",
    "===========================",
    "                           ",
    "                           ",
    "                           ",
    " ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
  ],
  //Bouncy house
  [

    '=                 ==  ==    ',
    '=                =      =    ',
    '=               =        =    ',
    '=              =          =    ',
    '=             =            =    ',
    '=            =              =    ',
    '=           =                =    ',
    '=          =                  =   ',
    '=   }     =                    =  ',
    '==========                      =',
    '         =                      =',
    '         =                      =',
    '         =                      =$',
    '         =       $       $      =$',
    '         =   lllllllllllllllll  =$',
    '         =   =  =  = ^ =  =  =  =',
    '         =                      =',
    '         =                      =',
    '         =$$$$$$$$$$   S$$$$$$$O=',
    '         llllllllllllllllllllllll',
    '         ',
    '         ',
    '         ',
    '         ',
    '         ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Booby trap
  [
    '=^^^^^^^^^^^^^^^^^^^^^^=',
    '=                      =',
    '=                      =',
    '=                      =',
    '=    $                 =',
    '=    l       $         =',
    '=   =O= } $  ^     $$ O=',
    '========================',

  ],
  //Staircase of doom
  [
    '=============================',
    '=                           =',
    '=                           =',
    '=                           =',
    '=                           =',
    '=         !                 =',
    '=    l                      =',
    '=   l                       =',
    '=  l   $                    =',
    '= l                         =',
    '=l^^^^^^^$$$$$$ }   $$$$^^^O=',
    '=============================',

  ],
  //Bouncing Around
  [
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=     $    =',
    '=     =    =',
    '=         $=',
    '=     ^   ==',
    '= $l       =',
    '= =      l =',
    '=^^^^    $ =',
    '=^^^^      =',
    '=      $  O=',
    '=====^^==ll=',
    '',
    '',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Look out Below
  [
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=          }              ',
    '=          =              ',
    '=          =   !          ',
    '=   lllllll=              ',
    '=     ^    =              ',
    '=     =    =              ',
    '=          =              ',
    '=          =              ',
    '=          =              ',
    '=   $$$$$  =              ',
    'llllllllllll     ^^   ^^ O',
    '              ============',
    '                          ',
    '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
  ],
  //Whoop de doo
  [
    '=',
    '=',
    '=',
    '=',
    '=',
    '=                                                               $',
    '=',
    '=                  $           !',
    '=                  k                                            }',
    '=                  =                                            =^^^^^^',
    '=      ^^^^',
    '=        =',
    '=        $     $              D',
    '=              =              D                             $              ===O',
    '=                             D                             l',
    '=                             D',
    '=$              $   $         D    $         $',
    '===llllllllll=========^^^^^^^^^=^^^^^^^^^=====',
    '',
    '',
    '',
    '                                                        l',
    '',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Healthy Hurdles
  [
    '=                                              O             ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=          =                                                 ',
    '=          =                                   l             ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=          =                                                 ',
    '=          =                                   l             ',
    '=          =                                   =             ',
    '=      ^   =^^^^^^^^^^^^^^^^^^^^^^^^^^                    ',
    '=                                                            ',
    '=          =                             $                   ',
    '=          ==                            l                   ',
    '=      $       $       $       $         =                   ',
    '=                                                            ',
    '=  l   l } l   l   l   l   l   l   l   l                     ',
    '========================================                     ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
  ],
  //Onion can Fly
  [
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =     !',
    '=                                                 $         =',
    '=                                                 l         =',
    '=                                                           =',
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=                                               $           =',
    '=               $                               l           =',
    '=               l                                          l=',
    '=                                                           =',
    '=                    l         l         l                  =',
    '=                                                           =',
    '=          $                                                =',
    '=          l                                                =',
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=    $                                                     $=',
    '=  } l  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ l=       $  }   ^       $     ^    }   $   ^    $    O',
    '================================================================================================================',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Free fallin'
  [
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=            l',
    '=',
    '=                        !',
    '=',
    '=',
    '=            l',
    '=',
    '=',
    '=',
    '=            $',
    '=            l',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=            l',
    '=',
    '=',
    '=',
    '=                        $             $      $    }  $           $           $    $ }          $        $           ',
    '=      }  l^^^^^^^^^^^^llllll^^^^^^^llllllllllllllllllllll^^^^^^^^ll^^^^^^llllllllllllll^^^^^^^^ll^^^^^^^ll^^^^^^^llO',
    '================================================================================================================',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Da brick wall
  [
    "=====                                        =  =  =    O",
    "=====                              $   ==l",
    "=====                              l      ",
    "=====          $}                  =      ",
    "=====          ==            $  l         ",
    "=====                   $    =            ",
    "=====                 llll                ",
    "=====        $                            ",
    "=======     ==                            ",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Leap O' Faith
  [
    "==========================================================================================================================",
    "=                  ^^^^^^^^^                                  ",
    "=                                                                                     } ",
    "=                                                                                ============",
    "=                   l                        }   ===           ===^^            ^^^^^^^^^^",
    "=                                            ==        ll                                        ",
    "=         =                               l                                 =                    =",
    "=                                                                         $                                    !",
    "=                 =                                                       ===",
    "= }  $$             ======           lll",
    "========                                                                                                       O",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Descending Tomfoolery
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=     $    $         $         $     }",
    "=     =    =         =         =     =",
    "^^==^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^=",
    "        ",
    "                                     !",
    "                                      ",
    "                    !       =        $",
    "                               ^^^^",
    "                               ====  =",
    "                    $             ^  ^",
    "                               ",
    "                                     ",
    "                    $              ==",
    "                 ",
    "                    =         ^^^^^^^^^^^^^^^^^",
    "",
    "                                     ",
    "                ^^^ ! ^^^     l    l",
    "",
    "                                       O",
    "                    =                   ",
    "                          =      =    =",
    "",
    "",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Now this is hard
  [
    "=",
    "=",
    "=",
    "=                                                                                                   O",
    "=                             ",
    "=                             ",
    "=                             ",
    "=                               $    =^^                                                       =",
    "=                               =^^^^",
    "=                             ",
    "=                          =^^             l     $   ",
    "=                                              ^^==^^                                        ll",
    "=                             ",
    "=                                                           } ",
    "=                                                        ======            }  $",
    "=                                                             ^^^^^^^^^^^======  ",
    "=   }  $               $                                                      ^^^^^^^^^^^====ll",
    "==========           lll                                   ",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //DON'T GET SPIKED
  [
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                             ",
    "=                             ",
    "=                             ",
    "=                  }                                            $           ",
    "=                 ===            $     $                  $      ",
    "=                              ==========                 == ",
    "=        l   $$          ",
    "=        $                                        !",
    "=           ^^^^^^            ",
    "=                                                 l                    $",
    "=",
    "=",
    "=       l $                                         $                  O",
    "===============                                   l                   ===",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  



  ],
  //Platform Chaos
  [
    '=         ^             ^^',
    '=         =             ==',
    '=         =             ==                              =',
    '=         =         k- ^==^                             =',
    '=       $ =      $ =========              !             =',
    '=        ^=             $         ^                     =',
    '=        ==             $         =                     =',
    '=                                 =                     =',
    '=                       =   l     =                     =',
    '=                                 =                    =',
    '=                   lll^          =                     =',
    '=                   =====         =                     =',
    '=                   D $$=         =                     =',
    '=                   D $$=         =       !             =',
    '=                  ======lll      =                     =',
    '=                                 =                     =',
    '=                                 =                     =',
    '=                                 =              O      =',
    '=                   ===           =                     =',
    '= } ^^^^^^^=^^^^^^^^^^^^^^^^^^^^^^=^^^^^   }            =',
    '=========================================================',

  ],
  //Enter the Secret Lair
  [
    "=                                                                          O ",
    "=                             ",
    "=                                                              $  ",
    "=                                                             ===",
    "=                                                                               ",
    "=                      ",
    "=                  $              ",
    "=                             $   -   k                    l",
    "=                                ====         $  }         $",
    "= $  $   $    }                                =====",
    "================                                           = ",
    "=              D        }",
    "=  $     $ }   D        l",
    "================    ",
    "=",    
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
  //Secret Lair
  [
    "=iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    "=",
    "=",
    "=",
    "=",
    "=                                                 ",
    "=                                                            D",
    "=                                                            D",
    "=                                                            D",
    "=                                                            D",
    "=                     }                $             $       D",
    "=         ^^^^^^^     ======^^^^====^^====^^^^====^^====^^====",
    "=                    ==                                       =",
    "=                   ==                                        =",
    "=                                                             =",
    "=   lll $llllll               $             $               DDD=",
    "=                  }   llllll===lllll=lllll===llllll=lllll=lDOD=",
    "=                  ===========================================D",
    "=          ",
    "=          =          $                    $                ",
    "=                    }",
    "=                DDD===        $           =              =  ",
    "=                D    ==^^=^^^^^^^=^^^^^^^^^^^^^^^^^^=^^^^^^^",
    "======^^^^^^^^^^^      =========================================",
    "                   l   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "                   k",
    "                                                            ",
    "                                                                  =",
    "                                                            ",
    "                                                            ",
    "                      =      =^^^lllll==llllll=^^^^^^^^====        ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  

  ],
  //Rollercoaster
  [
    "=iiiiiiiiiiiii             =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=        ^                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",             
    "=  $  =  =                 =",
    "=     =  =                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=  $  =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",             
    "=     =  =                 =",
    "=     =  =                 =",
    "=  $  = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=   $ = $=                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=     =  =                 =",
    "= $   = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=   <<=  =                 =",             
    "=  ==== l=  <<<<<<<<<<<<<<<=",
    "=     = $=                 =",             
    "=     =  =                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=        =                 =",             
    "=        =                 =",
    "=>>>>>>>l=OOOOOOOOOOOOOOOOO=",
    "============================",
  ],
  //Onion's got HOPS
  [
    
    "=",
    "=                                                         O                        ",
    "=                                                                     {",
    "=                                                                     =",        
    "=",
    "=",
    "=                                   $                                        {",
    "=                                                                            l",
    "=   }        $",
    "=^=^=^=^=^^^^                                                           $",
    "=                    !          =^^^^^^^^^  ^^^^^^^^^^^^^^^^^",
    "=                           ^^==                         =                 $",
    "=                      $                                  $                ",
    "=          ^^^^^^^^^^=                                                    l",
    "=                                          $$$}                     $",
    "=                                         =====          l  ====^^^^^^^^^^",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Cruisin' for a Bruisin'
  [
    
    "= ",
    "=",
    "=",
    "=",
    "=",
    "=                                     $ l  ",
    "=      =^^^^^^^^^^                    =                !",
    "=     =                     ^",
    "=    =",
    "=    =",
    "=   =",
    "=   =                       l",
    "= ! = $  }",
    "=   =    ===",
    "=   =         =             ",
    "=                          l",
    "=",
    "=                     -",
    "=                     l  ^",
    "=",
    "=",
    "=                         l",
    "=",
    "=",
    "=                          ^   l",
    "=",
    "=                            l",
    "=",
    "=                          $  ",
    "=",
    "=$         $               l",
    "=     $",
    "=              $",
    "=   $    $           $                               OOOOO",
    "========================iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii=====iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Mount Scallion
  [
    "=                                                                                                 =   =^^^^^^^^^$",
    "=                                                                                                =               =  =^^^",
    "=                                                                                                                      =^",
    "=                                                                                               ^^^^^=                  =^",
    "=                                                                                             =                          =^",
    "=                                                                                           ^=        ^^^^^^^      =^     =^",
    "=                                                                                          ^=                              =^",
    "=                                                                                          =                                =^",
    "=                                                                                         =                  $-$             =^",
    "=                                                                                         ^                  ===              =^",
    "=                                                                                         ^ ^^^^^^^==      ^^   ^^ !      ==   =^",
    "=                                                                                         ^                                     =^",
    "=                                                                                         ^                                      =^",
    "=                                                                                        $^         l                 ^^=         =^",
    "=                                                                                        l^        $     $    $                    =^",
    "=                                                                                         ^     ====================                =^^^^^^^^^",
    "=                                                                                         ^",
    "=                                                     ^^^^^^^^^^^^                  $^^^^^^                          O",
    "=                                                     ============           ^^^^^^^=",
    "=                                                     ^^^^^^^^^^^^          =",
    "=                                                                       ^  ^",
    "=                      $                               $$         $",
    "=                      =                              =========  ==",
    "=                      ^                              ^",
    "=                      ^                              ^",
    "=                      ^                              ^           }      l^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "=                     ^                              ^       ^^^^==",
    "=                     ^                              ^",
    "=          $     $    ^             $$$$$$$          ^",
    "========^^^^^^^^^^l   ^            =========      l",
    "",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //DROP
  [
    "=",
    "=",
    "=                    $",
    "=               $",
    "=",
    "=",
    "= =  =  =       =    =",
    "=                                               k",
    "=                                           ^^    ^^",
    "=     =                                     ^      ^",
    "=$     }          $                         ^   = ^^",
    "=========^^^^^^^^                      l",
    "=                                             $$ }",
    "=                   }                       ====== ",
    "=               =====",
    "=                                $      =                {",
    "=                     ^^^^^^^^^^^=^^^^^^^^^^^            = ",
    "=                         ",
    "=",
    "=",
    "=                                                $ ",
    "=                                                 }",
    "=                                              =  =  ",
    "=                                               ^^",
    "=",
    "=",
    "=                            ",
    "=                                  ^             }    $       ^       }",
    "=                            =  =     =     =    =    =     =   =     =   =   =  =  =",
    "=                                                                                =  =",
    "=                                                                                =$ =   ",
    "=                                                                                =  =",
    "=                                                                                =  =",
    "=                                                                               DDDDDD",
    "=              ",
    "=                                                                                 O ",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Tower of Pain
  [
    "=",
    "=",
    "=    ^                    $$                            k",
    "=    = }       ^^^===  ^^^^^^^^     }                  ===",
    "=    ===       ======================",
    "=    =         =                   D",
    "=    =         =  !                D         }",
    "=    =    ^    =                   D      llll",            
    "=    ======    =      ^  ^         D",
    "=    $$=      ^=     llllllllll=======",
    "=      =     ===               =",
    "=      =       =             O =",
    "=      =  ^  ^ =            ====",
    "=      =  llll =======         =",
    "=      =       =               =",
    "=      =       =             $$=",
    "=      =       =^^^^^^^^^^^^====",
    "=      =       =================",
    "=      =    ^===               =",
    "=      =    ==                 =",
    "=                              =",
    "=    }                     $$$ =",
    "================           ===",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Tricky timing
  [
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=     }                                     ",
    "==========D               =                      ",
    "=$$$$$$$$$D                            ",
    "=$$$$$$$$$D                                 ",
    "==========D                                     ",
    "=  ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^    }          ",
    "=                     ll           ==             !",
    "=           =                          ",
    "=            $                 $       ",
    "=                             ==      ",
    "=           k                                   DDDDD",
    "=           l         =                         D O D",
    "=                                               D = D",
    "iiiiiiiiiiiiii^^==^^iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Insane Precision
  [
    "", //don't make this easier
    "                          ^^   ^^^",
    "=                           $",
    "=",
    "=                        D",
    "=                        D   k  ",
    "=                        D",
    "=                     !  D",
    "=                        D     l",
    "=                        D     $",
    "=                     D  D ^^^   ^^^^^",
    "=$ }           ^     DOD       ", 
    "=====^^^^^^^^  =^^^^^===",
    "              $                l",
    "                        $",
    "                        =",
    "               }",
    "               ==",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //It's Not That Simple
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=                   ",
    "=",
    "=",
    "=                                                                     k",
    "=",
    "=            }                                      $",
    "=      $   =====                              ^     l                ^",
    "=          =   =",
    "=          i O =            $                            =",
    "= $        i   =^^^^^^^^^^^^=^^^^^^^^^^  ^^^^                       }", 
    "================                D      $       l                    l",
    "           =                    D",
    "           = O                  D",
    "           =================    =   ==^==     ===              =",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    ],
  //It's a long Drop
  [
  "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=", "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=", "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=",
    
    "=                                         ^^",//haha its a long fall
    "=                               l        ====",
    "=                       ^                                               O",
    "=                       ==                               ====           =",
    "==========       ^^  ^^^    ",
    "",
    "                      }",
    "                    ===   =",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Into the Abyss
  [
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=   -    =",
    "=  ===  = ",
    "=$  =$  =",
    "= ! =$! =",
    "=  $=$  =",
    "= $ =$  =",
    "=$  =$  =",
    "= $ =$  =",
    "=  $=$  =",
    "= $ =$  =",
    "=^  =$  =",
    "=$  =$  =",
    "=$  =$  =",
    "=$  =$  =",
    "=^  =$  =",
    "=$  =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =   =",
    "=   =$  =",
    "=   = $ =",
    "=   =  $=",
    "=   =  $=",
    "=   =$  =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =  $=",
    "=   = $ =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   =$  =",
    "=   = $ =",
    "=   =$  =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =^^^=",
    "=^O^=^O^=",
    "=========",
    
    
  ],
  //Enter the labyrinth
  [
    "=   =",
    "=   =",
    "=   =",
    "=   =",
    "=   =",
    "=   =",
    "=   =                                                      ============================================",
    "=   =                                                      =                                          =",
    "=   =                                                      =                                          =",
    "=   =                                                      =                                           ",
    "=   =                                                      =                                        O  ",
    "=   =                                                      =      }                  $           ======",
    "=   =                                                      =      =            =========^^^^^^^^^^^",//hardest
    "=   =                                                      =      =            =       ============",//possible
    "=   ===============================================        =      =            =       =",//jump :) (not anymore)
    "=   ^                              =              =        =      =                    =",
    "=                    }   ^         =       ^^^^^  ===================                  =",
    "=                $   =   =         =       =====                    =         l        =",
    "=                ^   =          =  $  ^                             =^^^^^^^^^=        =",
    "=                =   =          =     =                             ==============l    =",
    "=      ^^^^^^^   =   =^^^=^^^^^^=  lll=^  }   ^^       ^  ^         =            $     =",
    "=ll===============================================llllllllllllll==                     =",
    "                                                               =                       =",
    "                                                               =   }         ===       =",
    "                                                               ======^^^^^^^^^^^^^^^^^^=",
    "                                                                    ====================",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    
  ],
  //The Labyrinth
  [
  "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  "i                                                           i",
  "i                                                           i",
  "i                                                           i",
  "i                                                           i",
  "===========================  ================================",
  "=     =                 =                 =        =     =  =",//MAZE TIME! you can jump infinitely in this level,
  "=     =                 =           -   $ =        =     =  =",//someone do that or I will when im done
  "=        =============  ==========  =  ====  =  =  =  =  =  =",
  "=  =     =        =  =           =  =  =     =  =     =     =",
  "=  =     =        =  =           =  =  =     =  =     =     =",
  "=  =  ====  ====  =  ==========  =  ====  ====  ==========  =",
  "=  =  =        =  =        =  =  =  =     =  =  =     =     =",
  "=  =  =        =  =        =  =  =  =     =  =  =     =     =",
  "=  ====  =======  ====  =  =  =  =  =  ====  =  =  =  ====  =",
  "=     =  =  =     =     =     =  =  =  =     =  =  =     =  =",
  "=     =  =  =     =     =     =  =  =  =     =  =  =     =  =",
  "====  =  =  =  ====  ==========  =  =  =  ====  =  ====  =  =",
  "=     =     =  =     =           =     =  =     =     =  =  =",
  "=     =     =  =     =           =     =  =     =     =  =  =",
  "=  ====  ====  =  =  =  ==========  ====  =  ====  ====  =  =",
  "=        =     =  =        =     =        =        =     =  =",
  "=        =     =  =        =     =        =        =     =  =",
  "=  =======  =============  =  =  ==========  =======  ====  =",
  "=  =        =     =     =     =           =  =     =     =  =",
  "=  =        =     =     =     =   G       =  =     =     =  =",
  "=  =  ====  =  =  =  =  ================  ====  =  ====  =  =",
  "=  =  =     =  =     =     =        =           =        =  =",
  "=  =  =     =  =     =     =        =           =        =$$=",
  "=  =  ====  =  ==========  ====  =  =  ======================",
  "=  =     =  =  =        =     =  =  =  =  =           =     =",
  "=  =     =  =  =        =     =  =  =  =  =           =     =",
  "=  ====  ====  =  ====  ====  =  ====  =  =  =======  =  =  =",
  "=     =     =  =  =        =  =  =     =  =     =  =     =  =",
  "=     =     =  =  =        =  =  =     =  =     =  =     =  =",
  "====  ====  =  ====  ====  =  =  =  ====  ====  =  =======  =",
  "=  =     =  =        =     =  =        =     =        =     =",
  "=  =     =  =        =     =  =        =     =        =     =",
  "=  ====  =  ==========  ====  =======  =  =  =======  =  ====",
  "=     =  =  =        =     =     =  =  =  =     =     =     =",
  "=     =  =  =        =     =     =  =  =  =   G =     =     =",
  "=  =  =  =  =  =  =======  ====  =  =  ====  ====  =======  =",
  "=  =     =  =  =  =        =     =  =  =     =     =        =",
  "=  =     =  =  =  =        =     =  =  =     =     =        =",
  "=  =======  =  =  =  =======  ====  =  =  ====  ====  ====  =",
  "=  =     =     =     =  =     =     =  =     =  =  =  =  =  =",
  "=  =     =     =     =  =     =     =  =     =  =  =  =  =  =",
  "=  ====  =============  =  =======  =  ====  =  =  =  =  =  =",
  "=              =        =  =     =        =  =     =  =     =",
  "=        G     =        =  =     =        =  =     =  =     =",
  "=============  ====  =  =  =  =  =======  =  ====  =  =  ====",
  "=  =                 =  =     =     =        =     =  =  =  =",
  "=  =                 =  =     =     =        =     =  =  =  =",
  "=  =  ============================  ==========  ====  =  =  =",
  "=     =  =              =        =              =  =  =     =",
  "=     =  =              =        =              =  =  =     =",
  "=  ====  =  ==========  =  ====  =  =============  =  ====  =",
  "=        =           =     =  =  =                 =  =     =",
  "=        =           =     =  =  =                 =  =     =",
  "=======  ==========  =======  =  ===================  =======",
  "=     =           =  =     =                       =        =",
  "=     =           =  =     =             G         =        =",
  "=  =============  =  =  =  ======================  =======  =",
  "=                 =     =        =                          =",
  "=             k   =     =        =                          =",
  "=============================DDD============================",
  "                              ",
  "                              O  ",
  "",
  "",
  "iiiiiiiiiiiiiiiiiiiiiiiiiiiii i iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
  //Onion's Demise
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=                       ^^^    O",
    "=                ===============",
    "=                = = = = = = = =",
    "=                ===============",
    "=                = = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "================================iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
[
  "  ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ",
  "  =$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$= O",
  "=============================================================",
],[
"i       G                 iiiiii                                                   i",
"i                                                                                  i",
"i										   										   										   								i",
"i^======^  ^^== ===??===        == = === = ===????===   =^=^==   =====   = =  ==== i",
"i   v  v                ll  ll                i i                                  i",
"i                        ?      G   G                                              i",
"i										   										   										   								i",
"i										   										   										   								i",
"i      ==??==           ==l====                                                    i",
"i        ii                                                                        i",
"i										   										   										   								i",
"i                                G   G                                             i",
"i   ==?===    = == ===   i   ^====i===^       = ====  l ==?== ? l ===l ===  ====   i",
"i      i                                                                           i",
"i										   										   										   								i",
"i										   										   										   								i",
"i										   										   										   								i",
"iiiiiiiii      iiiii       iiiiiiiiiiiii         iiiiiiii      iiiiii         iiiiii",
"i										   										   										   								i",
"i										   										   										   								i",
"i										   										   										   								i",
"i										   										   										   								i",
"i    ll                         ll  lll       ll   lll    ll            lll  ll    i",
"i										   										   										   								i",
"i										   										   										   								i",
"i										   										   										   								i",
"i										   										   										   								i",
"i										   										   										   								i",
"i  =====  ===  == =====   ===  ===== ===   ===== ==   ===   == ======   =====    = i",
"i										   										   										   								i",
"i										   										   										   								i",
"i										   										   										   								i",
"i										   										   										   								i",
"i   ==i??==   ======  ??  ===== ^ = ^ =  =  ==??==   ===== ====  ==i==  ===??===ii i",
"i                     ii                                                           i",
"i                                                                           iiiiiiii",
"i       ll       l                                                                Oi",
"i                        ^                                                         i",
"i     l                  v               ^    ^   ^                                i",
"i                                                                                  i",
"i    ^     l    ^^^^lllll^^^ ^ ^^l^ ^ ^ l ^ l ^ l ^     ^ l ^    lll    l         li",
"i                                                                            iiiii i",
"i                                                                                 li",
"i                      v      l                                                    i",
"i             G    ^v^v^v^v^v           G                    v   v                 i",
"i====   ==  ^===^ =  ==  =  =  ===  ^=======^ == ^ ??  ?=  ==  =  =  =??==  =  l   i",
"i     l                           l             l  ==          l         l         i",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
	//We're Just Getting Started
[
"",
	"",
	"     =======================================================",
	"       =                                         =     =",
	"       =                                         =     =   O",
	"                        ===     ^  ===   ===  ^",
	"                  ^^    = ===   ====          =     ^     ^",
	"          ^  ^    ==    =       =             =     =     =",
	"     ^  llllllll  ==    =^^^^^^^=^^^^^^^^^^^^^=  ^  =  ^  =",
	"===============================================lllllllllllll",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	
	
]
  //end of level code 
]

const CHALLENGES = [
[
"=   = O             =",
"=   =               =",
"=   =====           =",
"=   = k =           =",
"=   =   =       D   =",
"=   =  ==       D   =",
"=   =   =       =====",
"=   ==  =           =",
"=   =               =",
"=   =               =",
"=   ========        =",
"=   =               =",
"=   =               =",
"=   =              ==",
"=                  ==",
"=                ^^==",
"=====================",
],
	]

const levelConf = {
  width: 64,
  height: 64,

  "=": () => [
    sprite("grass"),
    area(),
    solid(),
    scale(1),
    origin("bot"),
    "ground"
  ],
  "?": () => [
    sprite("fake"),
    area(),
    scale(1),
    origin("bot"),
    "ground"
  ],
  "$": () => [
    sprite("coin"),
    area(),
    origin("bot"),
    "coin",
  ],
  "^": () => [
    sprite("spike"),
    area(),
    solid(),
    origin("bot"),
    "danger",
  ], 
  "v": () => [
    sprite("dspike"),
    area(),
    solid(),
    origin("top"),
    "danger",
  ],
  "O": () => [
    sprite("portal"),
    area({ scale: 0.5, }),
    pos(0, -12),
    origin("bot"),
    "portal",
  ],
  "l": () => [
    sprite("jumpy"),
    origin("bot"),
    area(),
    "jumpy",
  ],
"h": () => [
    sprite("invisdanger"),
    origin("bot"),
    area(),
    "jumpy",
  ],
  "D": () => [
    sprite("door"),
    area(),
    solid(),
    origin("bot"),
    "door",
  ],
  "k": () => [
    sprite("key"),
    area(),
    origin("bot"),
    "key",
  ],
  ">": () => [
    sprite("block"),
    area(),
    solid(),
    origin("bot"),
    "right",
  ],
  "<": () => [
    sprite("block"),
    area(),
    solid(),
    origin("bot"),

    "left",
  ],
  ".": () => [
    sprite("block"),
    area(),
    solid(),
    origin("bot"),
  ],
  "{": () => [
    sprite("signpostl"),
    area(),
    origin("bot"), 
  ],
    "}": () => [
    sprite("signpostr"),
    area(),
    origin("bot"), 
  ],
    "-": () => [
    sprite("signposte"),
    area(),
    origin("bot"), 
  ],
    "i": () => [
    sprite("invisdanger"),
    area(),
    "danger",
    origin("bot"), 
  ],
  "S": () => [
    sprite("invisdanger"),
    area(),
    "spawn",
    origin("bot"), 
  ],
  "Q": () => [
    sprite("invisdanger"),
    area(),
    "arg",
    origin("bot"),
  ],
  "G": () => [
    sprite("ghost"),
    patrol(),
    "enemy",
    origin("bot"),
    area(), 
    body(), 
    ],
  "!": () => [
    sprite("darrow"),
    origin("bot"),
    area(),
  ],
  
}
function patrol(speed = 60, dir = 1) {
	return {
		id: "patrol",
		require: [ "pos", "area", ],
		add() {
			this.on("collide", (obj, col) => {
				if (col.isLeft() || col.isRight()) {
					dir = -dir
				}
			})
		},
		update() {
			this.move(speed * dir, 0)
		},
	}
}

export { LEVELS, levelConf }
