 //loadLevels()
const LEVELS = [
  //intro
  [
    '^                                                       =',
    '^                                                       =',
    '^                                                       =',
    '^                                                       =',
    '^                                                       =',
    '^                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=         l }  $$$      G ^      l     $$      }       O=',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==',

  ],
  //Classic
  [
    '	=                      ',
    '       ^^               ',
    '=                                                          ^^                ',
    '=                                                      ^^^^^^^^              ',
    '=                                                                            ',
    '=                               l$                                        ',
    '=                              ==      !                   =                  ',
    '=                            $                             =         ',
    '=                         ==  ^^                          ==          -',
    '=                    l $                                  ==$         =     l$ ',
    '=              $    ===  ^                      $      =  = =              ===',
    '=     $     } l                                       ==ll=        l    $    ',
    '=  l  ^    === ^^^   ^^^^^^^^^^^^^^^       ^      ^  =     = $   O=^^^^ =    ',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx====.        ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
    '','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',
    '                                                        QQQQ'
  ],
  //Flying for Coins
  [
    "=                          ",
    "=         ^    ^           ",
    "=                          ",
    "=                          ",
    "=    $    $    $    $     $",
    "=    $    $    $    $     $",
    "=                          ",
    "=         l                ",
    "=                l         ",
    "=                          ",
    "=                          ",
    "=     }      ^       l   O",
    "xx+xxxx+xxxx+xxxx+xxxx+xx==",
    "                           ",
    "                           ",
    "                           ",
    " ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
  ],
  //Bouncy house
  [

    '=                 ==  ==    ',
    '=                =      =    ',
    '=               =        =    ',
    '=              =          =    ',
    '=             =            =    ',
    '=            =              =    ',
    '=           =                =    ',
    '=          =                  =   ',
    '=   }     =                    =  ',
    'xx+xxxx+xx                      =',
    '         =                      =',
    '         =                      =',
    '         =                      =$',
    '         =       $       $      =$',
    '         =   lllllllllllllllll  =$',
    '         =   =  =  = ^ =  =  =  =',
    '         =                      =',
    '         =                      =',
    '         =$$$$$$$$$$   S$$$$$$$O=',
    '         llllllllllllllllllllllll',
    '         ',
    '         ',
    '         ',
    '         ',
    '         ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Booby trap
  [
    '=^^^^^^^^^^^^^^^^^^^^^^=',
    '=                      =',
    '=                      =',
    '=                      =',
    '=    $                 =',
    '=    l       $         =',
    '=   =O= } $  ^     $$ O=',
    'xx+xxxx+xxxx+xxxx+xx====',

  ],
  //Staircase of doom
  [
    'xx+xxxx+xxxx+xxxx+xxxx+xx====',
    '=                           =',
    '=                           =',
    '=                           =',
    '=                           =',
    '=         !                 =',
    '=    l                      =',
    '=   l                       =',
    '=  l   $                    =',
    '= l                         =',
    '=l^^^^^^^$$$$$$ }   $$$$^^^O=',
    'xx+xxxx+xxxx+xxxx+xxxx+xx====',

  ],
  //Bouncing Around
  [
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=     $    =',
    '=     =    =',
    '=         $=',
    '=     ^   ==',
    '= $l       =',
    '= =      l =',
    '=^^^^    $ =',
    '=^^^^      =',
    '=      $  O=',
    'xx+xx^^==ll=',
    '',
    '',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Look out Below
  [
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=          }              ',
    '=          =              ',
    '=          =   !          ',
    '=   lllllll=              ',
    '=     ^    =              ',
    '=     =    =              ',
    '=          =              ',
    '=          =              ',
    '=          =              ',
    '=   $$$$$  =              ',
    'llllllllllll     ^^   ^^ O',
    '              xx+xxxx+xx==',
    '                          ',
    '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
  ],
  //Whoop de doo
  [
    '=',
    '=',
    '=',
    '=',
    '=',
    '=                                                               $',
    '=',
    '=                  $           !',
    '=                  k                                            }',
    '=                  =                                            =^^^^^^',
    '=      ^^^^',
    '=        =',
    '=        $     $              D',
    '=              =              D                             $              ===O',
    '=                             D                             l',
    '=                             D',
    '=$              $   $         D    $         $',
    '===llllllllllxx+xx====^^^^^^^^^=^^^^^^^^^xx+xx',
    '',
    '',
    '',
    '                                                        l',
    '',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Healthy Hurdles
  [
    '=                                              O             ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=          =                                                 ',
    '=          =                                   l             ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=          =                                                 ',
    '=          =                                   l             ',
    '=          =                                   =             ',
    '=      ^   =^^^^^^^^^^^^^^^^^^^^^^^^^^                    ',
    '=                                                            ',
    '=          =                             $                   ',
    '=          ==                            l                   ',
    '=      $       $       $       $         =                   ',
    '=                                                            ',
    '=  l   l } l   l   l   l   l   l   l   l                     ',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx                     ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
  ],
  //Onion can Fly
  [
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =     !',
    '=                                                 $         =',
    '=                                                 l         =',
    '=                                                           =',
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=                                               $           =',
    '=               $                               l           =',
    '=               l                                          l=',
    '=                                                           =',
    '=                    l         l         l                  =',
    '=                                                           =',
    '=          $                                                =',
    '=          l                                                =',
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=    $                                                     $=',
    '=  } l  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ l=       $  }   ^       $     ^    }   $   ^    $    O',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Free fallin'
  [
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=            l',
    '=',
    '=                        !',
    '=',
    '=',
    '=            l',
    '=',
    '=',
    '=',
    '=            $',
    '=            l',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=            l',
    '=',
    '=',
    '=',
    '=                        $             $      $    }  $           $           $    $ }          $        $           ',
    '=      }  l^^^^^^^^^^^^llllll^^^^^^^llllllllllllllllllllll^^^^^^^^ll^^^^^^llllllllllllll^^^^^^^^ll^^^^^^^ll^^^^^^^llO',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Da brick wall
  [
    "xx+xx                                        =  =  =    O",
    "xx+xx                              $   ==l",
    "xx+xx                              l      ",
    "xx+xx          $}                  =      ",
    "xx+xx          ==            $  l         ",
    "xx+xx                   $    =            ",
    "xx+xx                 llll                ",
    "xx+xx        $                            ",
    "xx+xx==     ==                            ",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Leap O' Faith
  [
    "xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==",
    "=                  ^^^^^^^^^                                  ",
    "=                                                                                     } ",
    "=                                                                                xx+xxxx+xx==",
    "=                   l                        }   ===           ===^^            ^^^^^^^^^^",
    "=                                            ==        ll                                        ",
    "=         =                               l                                 =                    =",
    "=                                                                         $                                    !",
    "=                 =                                                       ===",
    "= }  $$             xx+xx=           lll",
    "xx+xx===                                                                                                       O",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Descending Tomfoolery
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=     $    $         $         $     }",
    "=     =    =         =         =     =",
    "^^==^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^=",
    "        ",
    "                                     !",
    "                                      ",
    "                    !       =        $",
    "                               ^^^^",
    "                               ====  =",
    "                    $             ^  ^",
    "                               ",
    "                                     ",
    "                    $              ==",
    "                 ",
    "                    =         ^^^^^^^^^^^^^^^^^",
    "",
    "                                     ",
    "                ^^^ ! ^^^     l    l",
    "",
    "                                       O",
    "                    =                   ",
    "                          =      =    =",
    "",
    "",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Now this is hard
  [
    "=",
    "=",
    "=",
    "=                                                                                                   O",
    "=                             ",
    "=                             ",
    "=                             ",
    "=                               $    =^^                                                       =",
    "=                               =^^^^",
    "=                             ",
    "=                          =^^             l     $   ",
    "=                                              ^^==^^                                        ll",
    "=                             ",
    "=                                                           } ",
    "=                                                        xx+xx=            }  $",
    "=                                                             ^^^^^^^^^^^xx+xx=  ",
    "=   }  $               $                                                      ^^^^^^^^^^^====ll",
    "xx+xxxx+xx           lll                                   ",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //DON'T GET SPIKED
  [
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                             ",
    "=                             ",
    "=                             ",
    "=                  }                                            $           ",
    "=                 ===            $     $                  $      ",
    "=                              xx+xxxx+xx                 == ",
    "=        l   $$          ",
    "=        $                                        !",
    "=           ^^^^^^            ",
    "=                                                 l                    $",
    "=",
    "=",
    "=       l $                                         $                  O",
    "xx+xxxx+xxxx+xx                                   l                   ===",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  



  ],
  //Platform Chaos
  [
    '=         ^             ^^',
    '=         =             ==',
    '=         =             ==                              =',
    '=         =         k- ^==^                             =',
    '=       $ =      $ xx+xx====              !             =',
    '=        ^=             $         ^                     =',
    '=        ==             $         =                     =',
    '=                                 =                     =',
    '=                       =   l     =                     =',
    '=                                 =                    =',
    '=                   lll^          =                     =',
    '=                   xx+xx         =                     =',
    '=                   D $$=         =                     =',
    '=                   D $$=         =       !             =',
    '=                  xx+xx=lll      =                     =',
    '=                                 =                     =',
    '=                                 =                     =',
    '=                                 =              O      =',
    '=                   ===           =                     =',
    '= } ^^^^^^^=^^^^^^^^^^^^^^^^^^^^^^=^^^^^   }            =',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==',

  ],
  //Enter the Secret Lair
  [
    "=                                                                          O ",
    "=                             ",
    "=                                                              $  ",
    "=                                                             ===",
    "=                                                                               ",
    "=                      ",
    "=                  $              ",
    "=                             $   -   k                    l",
    "=                                ====         $  }         $",
    "= $  $   $    }                                xx+xx",
    "xx+xxxx+xxxx+xx=                                           = ",
    "=              D        }",
    "=  $     $ }   D        l",
    "xx+xxxx+xxxx+xx=    ",
    "=",    
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
  //Secret Lair
  [
    "=iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    "=",
    "=",
    "=",
    "=",
    "=                                                 ",
    "=                                                            D",
    "=                                                            D",
    "=                                                            D",
    "=                                                            D",
    "=                     }                $             $       D",
    "=         ^^^^^^^     xx+xx=^^^^====^^====^^^^====^^====^^====",
    "=                    ==                                       =",
    "=                   ==                                        =",
    "=                                                             =",
    "=   lll $llllll               $             $               DDD=",
    "=                  }   llllll===lllll=lllll===llllll=lllll=lDOD=",
    "=                  xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx===D",
    "=          ",
    "=          =          $                    $                ",
    "=                    }",
    "=                DDD===        $           =              =  ",
    "=                D    ==^^=^^^^^^^=^^^^^^^^^^^^^^^^^^=^^^^^^^",
    "xx+xx=^^^^^^^^^^^      xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx=",
    "                   l   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "                   k",
    "                                                            ",
    "                                                                  =",
    "                                                            ",
    "                                                            ",
    "                      =      =^^^lllll==llllll=^^^^^^^^====        ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  

  ],
  //Rollercoaster
  [
    "=iiiiiiiiiiiii             =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=        ^                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",             
    "=  $  =  =                 =",
    "=     =  =                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=  $  =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",             
    "=     =  =                 =",
    "=     =  =                 =",
    "=  $  = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=   $ = $=                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=     =  =                 =",
    "= $   = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=   <<=  =                 =",             
    "=  ==== l=  <<<<<<<<<<<<<<<=",
    "=     = $=                 =",             
    "=     =  =                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=        =                 =",             
    "=        =                 =",
    "=>>>>>>>l=OOOOOOOOOOOOOOOOO=",
    "xx+xxxx+xxxx+xxxx+xxxx+xx===",
  ],
  //Onion's got HOPS
  [
    
    "=",
    "=                                                         O                        ",
    "=                                                                     {",
    "=                                                                     =",        
    "=",
    "=",
    "=                                   $                                        {",
    "=                                                                            l",
    "=   }        $",
    "=^=^=^=^=^^^^                                                           $",
    "=                    !          =^^^^^^^^^  ^^^^^^^^^^^^^^^^^",
    "=                           ^^==                         =                 $",
    "=                      $                                  $                ",
    "=          ^^^^^^^^^^=                                                    l",
    "=                                          $$$}                     $",
    "=                                         xx+xx          l  ====^^^^^^^^^^",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Cruisin' for a Bruisin'
  [
    
    "= ",
    "=",
    "=",
    "=",
    "=",
    "=                                     $ l  ",
    "=      =^^^^^^^^^^                    =                !",
    "=     =                     ^",
    "=    =",
    "=    =",
    "=   =",
    "=   =                       l",
    "= ! = $  }",
    "=   =    ===",
    "=   =         =             ",
    "=                          l",
    "=",
    "=                     -",
    "=                     l  ^",
    "=",
    "=",
    "=                         l",
    "=",
    "=",
    "=                          ^   l",
    "=",
    "=                            l",
    "=",
    "=                          $  ",
    "=",
    "=$         $               l",
    "=     $",
    "=              $",
    "=   $    $           $                               OOOOO",
    "xx+xxxx+xxxx+xxxx+xx====iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixx+xxiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Mount Scallion
  [
    "=                                                                                                 =   =^^^^^^^^^$",
    "=                                                                                                =               =  =^^^",
    "=                                                                                                                      =^",
    "=                                                                                               ^^^^^=                  =^",
    "=                                                                                             =                          =^",
    "=                                                                                           ^=        ^^^^^^^      =^     =^",
    "=                                                                                          ^=                              =^",
    "=                                                                                          =                                =^",
    "=                                                                                         =                  $-$             =^",
    "=                                                                                         ^                  ===              =^",
    "=                                                                                         ^ ^^^^^^^==      ^^   ^^ !      ==   =^",
    "=                                                                                         ^                                     =^",
    "=                                                                                         ^                                      =^",
    "=                                                                                        $^         l                 ^^=         =^",
    "=                                                                                        l^        $     $    $                    =^",
    "=                                                                                         ^     xx+xxxx+xxxx+xxxx+xx                =^^^^^^^^^",
    "=                                                                                         ^",
    "=                                                     ^^^^^^^^^^^^                  $^^^^^^                          O",
    "=                                                     xx+xxxx+xx==           ^^^^^^^=",
    "=                                                     ^^^^^^^^^^^^          =",
    "=                                                                       ^  ^",
    "=                      $                               $$         $",
    "=                      =                              xx+xx====  ==",
    "=                      ^                              ^",
    "=                      ^                              ^",
    "=                      ^                              ^           }      l^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "=                     ^                              ^       ^^^^==",
    "=                     ^                              ^",
    "=          $     $    ^             $$$$$$$          ^",
    "xx+xx===^^^^^^^^^^l   ^            xx+xx====      l",
    "",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //DROP
  [
    "=",
    "=",
    "=                    $",
    "=               $",
    "=",
    "=",
    "= =  =  =       =    =",
    "=                                               k",
    "=                                           ^^    ^^",
    "=     =                                     ^      ^",
    "=$     }          $                         ^   = ^^",
    "xx+xx====^^^^^^^^                      l",
    "=                                             $$ }",
    "=                   }                       xx+xx= ",
    "=               xx+xx",
    "=                                $      =                {",
    "=                     ^^^^^^^^^^^=^^^^^^^^^^^            = ",
    "=                         ",
    "=",
    "=",
    "=                                                $ ",
    "=                                                 }",
    "=                                              =  =  ",
    "=                                               ^^",
    "=",
    "=",
    "=                            ",
    "=                                  ^             }    $       ^       }",
    "=                            =  =     =     =    =    =     =   =     =   =   =  =  =",
    "=                                                                                =  =",
    "=                                                                                =$ =   ",
    "=                                                                                =  =",
    "=                                                                                =  =",
    "=                                                                               DDDDDD",
    "=              ",
    "=                                                                                 O ",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Tower of Pain
  [
    "=",
    "=",
    "=    ^                    $$                            k",
    "=    = }       ^^^===  ^^^^^^^^     }                  ===",
    "=    ===       xx+xxxx+xxxx+xxxx+xx==",
    "=    =         =                   D",
    "=    =         =  !                D         }",
    "=    =    ^    =                   D      llll",            
    "=    xx+xx=    =      ^  ^         D",
    "=    $$=      ^=     llllllllllxx+xx==",
    "=      =     ===               =",
    "=      =       =             O =",
    "=      =  ^  ^ =            ====",
    "=      =  llll xx+xx==         =",
    "=      =       =               =",
    "=      =       =             $$=",
    "=      =       =^^^^^^^^^^^^====",
    "=      =       xx+xxxx+xxxx+xx==",
    "=      =    ^===               =",
    "=      =    ==                 =",
    "=                              =",
    "=    }                     $$$ =",
    "xx+xxxx+xxxx+xx=           ===",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Tricky timing
  [
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=     }                                     ",
    "xx+xxxx+xxD               =                      ",
    "=$$$$$$$$$D                            ",
    "=$$$$$$$$$D                                 ",
    "xx+xxxx+xxD                                     ",
    "=  ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^    }          ",
    "=                     ll           ==             !",
    "=           =                          ",
    "=            $                 $       ",
    "=                             ==      ",
    "=           k                                   DDDDD",
    "=           l         =                         D O D",
    "=                                               D = D",
    "iiiiiiiiiiiiii^^==^^iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Insane Precision
  [
    "", //don't make this easier
    "                          ^^   ^^^",
    "=                           $",
    "=",
    "=                        D",
    "=                        D   k  ",
    "=                        D",
    "=                     !  D",
    "=                        D     l",
    "=                        D     $",
    "=                     D  D ^^^   ^^^^^",
    "=$ }           ^     DOD       ", 
    "xx+xx^^^^^^^^  =^^^^^===",
    "              $                l",
    "                        $",
    "                        =",
    "               }",
    "               ==",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //It's Not That Simple
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=                   ",
    "=",
    "=",
    "=                                                                     k",
    "=",
    "=            }                                      $",
    "=      $   xx+xx                              ^     l                ^",
    "=          =   =",
    "=          i O =            $                            =",
    "= $        i   =^^^^^^^^^^^^=^^^^^^^^^^  ^^^^                       }", 
    "xx+xxxx+xxxx+xx=                D      $       l                    l",
    "           =                    D",
    "           = O                  D",
    "           xx+xxxx+xxxx+xx==    =   ==^==     ===              =",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    ],
  //It's a long Drop
  [
  "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=", "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=", "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=",
    
    "=                                         ^^",//haha its a long fall
    "=                               l        ====",
    "=                       ^                                               O",
    "=                       ==                               ====           =",
    "xx+xxxx+xx       ^^  ^^^    ",
    "",
    "                      }",
    "                    ===   =",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Into the Abyss
  [
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=   -    =",
    "=  ===  = ",
    "=$  =$  =",
    "= ! =$! =",
    "=  $=$  =",
    "= $ =$  =",
    "=$  =$  =",
    "= $ =$  =",
    "=  $=$  =",
    "= $ =$  =",
    "=^  =$  =",
    "=$  =$  =",
    "=$  =$  =",
    "=$  =$  =",
    "=^  =$  =",
    "=$  =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =   =",
    "=   =$  =",
    "=   = $ =",
    "=   =  $=",
    "=   =  $=",
    "=   =$  =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =  $=",
    "=   = $ =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   =$  =",
    "=   = $ =",
    "=   =$  =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =^^^=",
    "=^O^=^O^=",
    "xx+xx====",
    
    
  ],
  //Enter the labyrinth
  [
    "=   =",
    "=   =",
    "=   =",
    "=   =",
    "=   =",
    "=   =",
    "=   =                                                      xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx====",
    "=   =                                                      =                                          =",
    "=   =                                                      =                                          =",
    "=   =                                                      =                                           ",
    "=   =                                                      =                                        O  ",
    "=   =                                                      =      }                  $           xx+xx=",
    "=   =                                                      =      =            xx+xx====^^^^^^^^^^^",//hardest
    "=   =                                                      =      =            =       xx+xxxx+xx==",//possible
    "=   xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==        =      =            =       =",//jump :) (not anymore)
    "=   ^                              =              =        =      =                    =",
    "=                    }   ^         =       ^^^^^  xx+xxxx+xxxx+xx====                  =",
    "=                $   =   =         =       xx+xx                    =         l        =",
    "=                ^   =          =  $  ^                             =^^^^^^^^^=        =",
    "=                =   =          =     =                             xx+xxxx+xx====l    =",
    "=      ^^^^^^^   =   =^^^=^^^^^^=  lll=^  }   ^^       ^  ^         =            $     =",
    "=llxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==llllllllllllll==                     =",
    "                                                               =                       =",
    "                                                               =   }         ===       =",
    "                                                               xx+xx=^^^^^^^^^^^^^^^^^^=",
    "                                                                    xx+xxxx+xxxx+xxxx+xx",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    
  ],
  //The Labyrinth
  [
  "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  "i                                                           i",
  "i                                                           i",
  "i                                                           i",
  "i                                                           i",
  "xx+xxxx+xxxx+xxxx+xxxx+xx==  xx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==",
  "=     =                 =                 =        =     =  =",//MAZE TIME! you can jump infinitely in this level,
  "=     =                 =           -   $ =        =     =  =",//someone do that or I will when im done
  "=        xx+xxxx+xx===  xx+xxxx+xx  =  ====  =  =  =  =  =  =",
  "=  =     =        =  =           =  =  =     =  =     =     =",
  "=  =     =        =  =           =  =  =     =  =     =     =",
  "=  =  ====  ====  =  xx+xxxx+xx  =  ====  ====  xx+xxxx+xx  =",
  "=  =  =        =  =        =  =  =  =     =  =  =     =     =",
  "=  =  =        =  =        =  =  =  =     =  =  =     =     =",
  "=  ====  xx+xx==  ====  =  =  =  =  =  ====  =  =  =  ====  =",
  "=     =  =  =     =     =     =  =  =  =     =  =  =     =  =",
  "=     =  =  =     =     =     =  =  =  =     =  =  =     =  =",
  "====  =  =  =  ====  xx+xxxx+xx  =  =  =  ====  =  ====  =  =",
  "=     =     =  =     =           =     =  =     =     =  =  =",
  "=     =     =  =     =           =     =  =     =     =  =  =",
  "=  ====  ====  =  =  =  xx+xxxx+xx  ====  =  ====  ====  =  =",
  "=        =     =  =        =     =        =        =     =  =",
  "=        =     =  =        =     =        =        =     =  =",
  "=  xx+xx==  xx+xxxx+xx===  =  =  xx+xxxx+xx  xx+xx==  ====  =",
  "=  =        =     =     =     =           =  =     =     =  =",
  "=  =        =     =     =     =   G       =  =     =     =  =",
  "=  =  ====  =  =  =  =  xx+xxxx+xxxx+xx=  ====  =  ====  =  =",
  "=  =  =     =  =     =     =        =           =        =  =",
  "=  =  =     =  =     =     =        =           =        =$$=",
  "=  =  ====  =  xx+xxxx+xx  ====  =  =  xx+xxxx+xxxx+xxxx+xx==",
  "=  =     =  =  =        =     =  =  =  =  =           =     =",
  "=  =     =  =  =        =     =  =  =  =  =           =     =",
  "=  ====  ====  =  ====  ====  =  ====  =  =  xx+xx==  =  =  =",
  "=     =     =  =  =        =  =  =     =  =     =  =     =  =",
  "=     =     =  =  =        =  =  =     =  =     =  =     =  =",
  "====  ====  =  ====  ====  =  =  =  ====  ====  =  xx+xx==  =",
  "=  =     =  =        =     =  =        =     =        =     =",
  "=  =     =  =        =     =  =        =     =        =     =",
  "=  ====  =  xx+xxxx+xx  ====  xx+xx==  =  =  xx+xx==  =  ====",
  "=     =  =  =        =     =     =  =  =  =     =     =     =",
  "=     =  =  =        =     =     =  =  =  =   G =     =     =",
  "=  =  =  =  =  =  xx+xx==  ====  =  =  ====  ====  xx+xx==  =",
  "=  =     =  =  =  =        =     =  =  =     =     =        =",
  "=  =     =  =  =  =        =     =  =  =     =     =        =",
  "=  xx+xx==  =  =  =  xx+xx==  ====  =  =  ====  ====  ====  =",
  "=  =     =     =     =  =     =     =  =     =  =  =  =  =  =",
  "=  =     =     =     =  =     =     =  =     =  =  =  =  =  =",
  "=  ====  xx+xxxx+xx===  =  xx+xx==  =  ====  =  =  =  =  =  =",
  "=              =        =  =     =        =  =     =  =     =",
  "=        G     =        =  =     =        =  =     =  =     =",
  "xx+xxxx+xx===  ====  =  =  =  =  xx+xx==  =  ====  =  =  ====",
  "=  =                 =  =     =     =        =     =  =  =  =",
  "=  =                 =  =     =     =        =     =  =  =  =",
  "=  =  xx+xxxx+xxxx+xxxx+xxxx+xx===  xx+xxxx+xx  ====  =  =  =",
  "=     =  =              =        =              =  =  =     =",
  "=     =  =              =        =              =  =  =     =",
  "=  ====  =  xx+xxxx+xx  =  ====  =  xx+xxxx+xx===  =  ====  =",
  "=        =           =     =  =  =                 =  =     =",
  "=        =           =     =  =  =                 =  =     =",
  "xx+xx==  xx+xxxx+xx  xx+xx==  =  xx+xxxx+xxxx+xx====  xx+xx==",
  "=     =           =  =     =                       =        =",
  "=     =           =  =     =             G         =        =",
  "=  xx+xxxx+xx===  =  =  =  xx+xxxx+xxxx+xxxx+xx==  xx+xx==  =",
  "=                 =     =        =                          =",
  "=             k   =     =        =                          =",
  "xx+xxxx+xxxx+xxxx+xxxx+xx====DDDxx+xxxx+xxxx+xxxx+xxxx+xx===",
  "                              ",
  "                              O  ",
  "",
  "",
  "iiiiiiiiiiiiiiiiiiiiiiiiiiiii i iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
  //Onion's Demise
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=                       ^^^    O",
    "=                xx+xxxx+xxxx+xx",
    "=                = = = = = = = =",
    "=                xx+xxxx+xxxx+xx",
    "=                = = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "xx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
[
  "  ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ",
  "  =$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$=$= O",
  "xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx=",
],

	//We're Just Getting Started
[
	"     =",
	"     =",
	"     xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx",
	"       =                                         =     =        =",
	"       =                                         =     =        =",
	"                        ===     ^  ===   ===  ^                 =",
	"                  ^^    = ===   ====          =     ^     ^     =",
	"          ^  ^    ==    =       =             =     =     =     =",
	"     ^  llllllll  ==    =^^^^^^^=^^^^^^^^^^^^^=  ^  =  ^  =     =",
	"xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==lllllllllllll OO =",
],
	[
	"=    xx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==",
	"=    =                     =  =      ",
	"=    =    k                =  =      ",
	"=    =   xx+xx====  v      =O        ",
	"=    =   vv                =         ",
	"=    =                     =         ",
	"=    =                     =^^^^^^   ",
	"=    =              l      xx+xx===  ",
	"=    =   ^                 D         ",
	"=    =   =ll=              D         ",
	"=                          xx+xx===  ",
	"=                          =         ",
	"=        ^^^^^^^^^^^^^^^^^^=^^^^^^^^^",
	"xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==",
		],
	[
"=   = O             =",
"=   =               =",
"=   xx+xx           =",
"=   = k =           =",
"=   =   =       D   =",
"=   =   =       D   =",
"=   =   =       xx+xx",
"=   ==  =           =",
"=   =               =",
"=   =               =",
"=   xx+xx===        =",
"=   =               =",
"=   =               =",
"=   =              ==",
"=                  ==",
"=                ^^==",
"xx+xxxx+xxxx+xxxx+xx=",
		],
	[
"xx+xxxx+xx=   OO   =",
"=         =   vv   =",
"=         =        =",
"=    ^^  ^=        =",
"xx+xx==  ==        =",
"=    $=  D=^^^     =",
"=    $=  D====ll   =",
"=   ===  D         =",
"=        D         =",
"=        D         =",
"=k  ^^^  D  ^^  ^^^=",
"xx+xxxx+xxxx+xxxx+xx",

		],
	[
"=  =            ^  ^^^  ^^^^^  ^^",
"=  =            xx+xxxx+xx===  ==",
"=  =            =               =",
"=  =     =      =               =",
"=  =            =   ^^          =",
"=  =            =  =ll===       =",
"=  =            =       =       =",
"=  =         =  =       =       =",
"=  =vv=      =  =   ^^  =^^  ^^^=",
"=  =     xx+xxxx+xx===  xx+xxxx+xx",
"=  =     =",
"=  =     =            OO",
"=  =lll===",
"=  =     =",
"=  =     =",
"=      = =",
"=      = =",
"xx+xxxx+xx",


		],
	//Freaky Deeky
	//Eli, if you even touch this level, I will doxx you and your family, call up my uncle and tell him to barragre you with so many scam calls that you will never have a moment of peace ever again. Comprende amigo?
[
"i    G                    iiiiii                                                   i",
"i                                                                                  i",
"i^      ^        h                                                                  i",
"ixx+xx===  ^^== ===??===    ==  === = ===????===   =^=^==   xx+xx   = =  ====  i",
"i   v  v               hh  ll                i i                                  i",
"i                        ?                                                         i",
"i                                                                                  i",
"i                                                                                  i",
"i      ==??==      hh    ==l====       xx+xx??                                i",
"i        ii        ll                      ^^                                        i",
"i                                                                                  i",
"i                            ^       G^                                             i",
"i   ==?===    i==??===   i   xx+xxi====iiii   =i====  l ==?== ? l ===l ===  ====   i",
"i       i                                                                         i",
"i                                                                                  i",
"i                                                                                  i",
"i                                                                                  i",
"iii????hh      ii??i       ii?===h?ii         ii===h=ii      i???ii         ii??ii",
"i                                                                                  i",
"$   xx+xx                              ^     l                ^                    i",
"=          =   =                                                                   i",
"=          i  =            $                            =                          i",
"=hh       i   =^^^^^^^^^^^^=^^^^^^^^^^  ^^^^                                       i", 
"                                                                                   i",
"     ==?==                h      $       l                    l                    i",
"                                                                                   i",
"i                                                                                  i",
"i ^         =     h               h                                                i",
"i                                                                                  i",
"           =             h      h                                                  i",
"i                                                                                  i",
"           ===??===hxx+xx==    =   ==^==     ===              =                    i",                             
"i                                                                                  i",
"i  ==??=  =h=  == ==??==   =?=  ==?=^     ^==??= ==i  ===   == ==??==   ==??=    = i",
"",
"====  =  ====  ====    ====  =  =  xx+xx==  = i  ==                                i",
"",
"",
  "=     ?     ?  =  =        i  =  ?     ?  =     =  h     =  =                     i",
"",
"",
  "?     =     i  =  ? h      ?  =  i     h  =     ?  =     =  =                     i",
"",
"",
  "====  ====  =  ==h===  =  =  =  ====  ====  ?  ===h===  =                     i",
"",
  "=  =     =  =        =     i  =            i                                     i",
"                                                                                    i",
"i   ==i??==  =??xx+xx  ??  xx+xx ^ = ^ =  =  ==??==   xx+xx ====  ==i==  ===??===ii i",
"",
"                        ===     ^  ===   ===  ^                 =",
"",
"",
	"                  ^^    = ===   ====          =     h     i     =",
"",
"",
	"          ^  ^    ==    =       =             ?     =     =     =",
"",
"",
"        ^   G   ^                                                    iiiiiiiiiiii===i ",
"i       ===hh===  ====        ==??=        =??==        ===                         i",
"                                                                                    O",
"i    ^     l    ^^^^lllll^^^ ^ ^^l^ ^ ^ l ^ l ^ l ^     ^ h ^                            i",
"i                                                                                 h      i",
"i                                                                                  iiiiiii",
"i                      v      l                                                    i",
"i                  ^v^v^v^v^v           G                    v   v                 i",
"i====   ==  i===i =  ==  =  =  ===  ^xx+xx==^ == ^ ??  ?=  ==  =  =  =??==  =  h   i",
"i     l                           l             l  ==          l         l         i",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
	//dodging and weaving
[
"=              =",
"=              =",
"=              =",
"=              =",
"=  $$$$        =",	
"=              =",
"xx+xxxx+xx=    =",
"          =  ^^=",
"          =    =",
"          = $$ =",
"          =    =",
"          =^^  =",
"          =    =",
"          = $$ =",
"          =   l=",
"          =    =",
"          =    =",
"          =^$$^=",
"          =^$$^=",
"          =^$$^=",
"          =OOOO=",
"          xx+xx",

],
  //end of level code 
]

const CHALLENGES = [
[
"=   = O             =",
"=   =               =",
"=   xx+xx           =",
"=   = k =           =",
"=   =   =       D   =",
"=   =  l=       D   =",
"=   =   =       xx+xx",
"=   ==  =           =",
"=   =               =",
"=   =               =",
"=   xx+xx===        =",
"=   =               =",
"=   =               =",
"=   =              ==",
"=                  ==",
"=                ^^==",
"xx+xxxx+xxxx+xxxx+xx=",
],
	]

const levelConf = {
  width: 64,
  height: 64,

  "=": () => [
    sprite("grass"),
    area(),
    solid(),
    scale(1),
    origin("bot"),
    
    "ground"
  ],
"+": ()=> [
	sprite("grass5"),
	rect(32 * 5, 32),
	area(),
	solid(),
	origin("bot"),
	"ground",
],
  "?": () => [
    sprite("fake"),
    area(),
    scale(1),
    origin("bot"),
    
    "ground"
  ],
  "$": () => [
    sprite("coin"),
    area(),
    origin("bot"),
    
    "coin",
  ],
  "^": () => [
    sprite("spike"),
    area(),
    solid(),
    origin("bot"),
    
    "danger",
  ], 
  "v": () => [
    sprite("dspike"),
    area(),
    solid(),
    origin("top"),
    
    "danger",
  ],
  "O": () => [
    sprite("portal"),
    area({ scale: 0.5, }),
    pos(0, -12),
    origin("bot"),
    
    "portal",
  ],
  "l": () => [
    sprite("jumpy"),
    origin("bot"),
    area(),
    
    "jumpy",
  ],
"h": () => [
    sprite("invisdanger"),
    origin("bot"),
    area(),
    
    "jumpy",
  ],
  "D": () => [
    sprite("door"),
    area(),
    solid(),
    origin("bot"),
    
    "door",
  ],
  "k": () => [
    sprite("key"),
    area(),
    origin("bot"),
    
    "key",
  ],
  ">": () => [
    sprite("block"),
    area(),
    solid(),
    origin("bot"),
    
    "right",
  ],
  "<": () => [
    sprite("block"),
    area(),
    solid(),
    origin("bot"),
    
    "left",
  ],
  ".": () => [
    sprite("block"),
    area(),
    solid(),
    
    origin("bot"),
  ],
  "{": () => [
    sprite("signpostl"),
    area(),
    
    origin("bot"), 
  ],
    "}": () => [
    sprite("signpostr"),
    area(),
    
    origin("bot"), 
  ],
    "-": () => [
    sprite("signposte"),
    area(),
    
    origin("bot"), 
  ],
    "i": () => [
    sprite("invisdanger"),
    area(),
    "danger",
    
    origin("bot"), 
  ],
  "S": () => [
    sprite("invisdanger"),
    area(),
    "spawn",
    
    origin("bot"), 
  ],
  "Q": () => [
    sprite("invisdanger"),
    area(),
    "arg",
    
    origin("bot"),
  ],
  "G": () => [
    sprite("ghost"),
    patrol(),
    "enemy",
    origin("bot"),
    area(), 
    body(), 
    
    ],
  "!": () => [
    sprite("darrow"),
    origin("bot"),
    area(),
  ],
  
}
function patrol(speed = 60, dir = 1) {
	return {
		id: "patrol",
		require: [ "pos", "area", ],
		add() {
			this.on("collide", (obj, col) => {
				if (col.isLeft() || col.isRight()) {
					dir = -dir
				}
			})
		},
		update() {
			this.move(speed * dir, 0)
		},
	}
}

export { LEVELS, levelConf }
