// Auto-generated by generate-sw.js — do not edit manually
// Cache hash: bbad89e0
const CACHE_NAME = 'onions-life-bbad89e0';

const PRECACHE_ASSETS = [
  "/",
  "/assets/apl386.woff2",
  "/assets/sounds/OverworldlyFoe.mp3",
  "/assets/sounds/bug.mp3",
  "/assets/sounds/error.mp3",
  "/assets/sounds/hit.mp3",
  "/assets/sounds/music.ogg",
  "/assets/sounds/portal.mp3",
  "/assets/sounds/score.mp3",
  "/assets/sounds/spring.mp3",
  "/assets/sprites/achBtn.png",
  "/assets/sprites/achievement_badge_64px.png",
  "/assets/sprites/arrowl.png",
  "/assets/sprites/arrowr.png",
  "/assets/sprites/bag.png",
  "/assets/sprites/bigonion.png",
  "/assets/sprites/block.png",
  "/assets/sprites/boom.png",
  "/assets/sprites/chevronleft.png",
  "/assets/sprites/cloud.png",
  "/assets/sprites/coasterLeft.png",
  "/assets/sprites/coasterRight.png",
  "/assets/sprites/coin.png",
  "/assets/sprites/darrow.png",
  "/assets/sprites/dj.png",
  "/assets/sprites/door.png",
  "/assets/sprites/dspike.png",
  "/assets/sprites/eggplant-onion.png",
  "/assets/sprites/fake.png",
  "/assets/sprites/ghostiny.png",
  "/assets/sprites/ghosty.png",
  "/assets/sprites/gigagantrum.png",
  "/assets/sprites/grass.png",
  "/assets/sprites/grass25.png",
  "/assets/sprites/grass5.png",
  "/assets/sprites/heart.png",
  "/assets/sprites/home.png",
  "/assets/sprites/invis25.png",
  "/assets/sprites/invisdanger.png",
  "/assets/sprites/invisspike.png",
  "/assets/sprites/jumpbutton.png",
  "/assets/sprites/jumpleft.png",
  "/assets/sprites/jumpright.png",
  "/assets/sprites/jumpy.png",
  "/assets/sprites/key.png",
  "/assets/sprites/keyboard_b.svg",
  "/assets/sprites/keyboard_r.svg",
  "/assets/sprites/lightbulb.png",
  "/assets/sprites/lockedarrowr.png",
  "/assets/sprites/lvlbtn.png",
  "/assets/sprites/lvlselect.png",
  "/assets/sprites/magic-onion.png",
  "/assets/sprites/nopirates.png",
  "/assets/sprites/onion-beach.png",
  "/assets/sprites/onion-blue.png",
  "/assets/sprites/onion-dark.png",
  "/assets/sprites/onion-gold.png",
  "/assets/sprites/onion-ocean.png",
  "/assets/sprites/onion-pumpkin.png",
  "/assets/sprites/onion-secret.png",
  "/assets/sprites/onion-watermelon.png",
  "/assets/sprites/onion-watermelon2.png",
  "/assets/sprites/onion.png",
  "/assets/sprites/onionInvert.png",
  "/assets/sprites/portal.png",
  "/assets/sprites/portal1.png",
  "/assets/sprites/pumpkin-onion.png",
  "/assets/sprites/replay.png",
  "/assets/sprites/rightchevron.png",
  "/assets/sprites/sand.png",
  "/assets/sprites/signposte.png",
  "/assets/sprites/signpostl.png",
  "/assets/sprites/signpostr.png",
  "/assets/sprites/skinsBtn.png",
  "/assets/sprites/snow.png",
  "/assets/sprites/spike.png",
  "/assets/sprites/spike3.png",
  "/assets/sprites/spike9.png",
  "/assets/sprites/startbtn.png",
  "/assets/sprites/trophy.png",
  "/assets/sprites/water.png",
  "/assets/sprites/winSpinBtn.png",
  "/game-main.js",
  "/index.html",
  "/manifest.json",
  "/offline.html",
  "/scripts/achievement.js",
  "/scripts/assets.js",
  "/scripts/bagsLife/assets.js",
  "/scripts/bagsLife/levels.js",
  "/scripts/batchedGroundRenderer.js",
  "/scripts/challenges.js",
  "/scripts/coinManager.js",
  "/scripts/collisionBatcher.js",
  "/scripts/easySwimming.js",
  "/scripts/generalOptimizations.js",
  "/scripts/hacker-campaign/assets.js",
  "/scripts/hacker-campaign/index.html",
  "/scripts/hacker-campaign/levels.js",
  "/scripts/levelOptimizer.js",
  "/scripts/levelTileBatcher.js",
  "/scripts/levelnames.js",
  "/scripts/levels.js",
  "/scripts/mobilePerformanceMonitor.js",
  "/scripts/optimizedTouchControls.js",
  "/scripts/packHandler.js",
  "/scripts/performanceConfig.js",
  "/scripts/realisticSwimming.js",
  "/scripts/resourcePaths.js",
  "/scripts/simpleRealisticSwimming.js",
  "/scripts/simpleWaterPhysics.js",
  "/scripts/skinManager.js",
  "/scripts/touchCode.js",
  "/scripts/touchControlCustomizer.js",
  "/scripts/waterFixer.js",
  "/scripts/winSpins.js"
];

// Critical CDN modules to pre-cache on install (game won't load without these)
const PRECACHE_CDN = [
  "https://unpkg.com/kaplay@4000.0.0-alpha.5/dist/kaplay.mjs"
];

// CDN origins to cache on first fetch (for non-critical imports like Supabase)
const CACHEABLE_CDN = [
  'https://unpkg.com',
  'https://esm.sh',
];

// --- Install: pre-cache all game assets + critical CDN modules ---
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => {
        // Pre-cache CDN modules with cross-origin fetch
        const cdnPromises = PRECACHE_CDN.map((url) =>
          fetch(url, { mode: 'cors' })
            .then((resp) => cache.put(url, resp))
            .catch((err) => console.warn('Failed to pre-cache CDN:', url, err))
        );
        return Promise.all([cache.addAll(PRECACHE_ASSETS), ...cdnPromises]);
      })
      .then(() => self.skipWaiting())
  );
});

// --- Activate: delete old caches, claim clients immediately ---
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(
        names
          .filter((n) => n.startsWith('onions-life-') && n !== CACHE_NAME)
          .map((n) => caches.delete(n))
      )
    ).then(() => self.clients.claim())
  );
});

// --- Fetch strategies ---
self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Only handle GET
  if (request.method !== 'GET') return;

  // Never cache analytics or remote APIs
  if (url.hostname.includes('google') || url.hostname.includes('gtag')) return;
  if (url.hostname.includes('appwrite') || url.hostname.includes('supabase')) return;

  // HTML navigation: network-first so new deploys are picked up, cache fallback for offline
  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request));
    return;
  }

  // CDN resources (Kaplay engine): stale-while-revalidate
  if (CACHEABLE_CDN.some((origin) => request.url.startsWith(origin))) {
    event.respondWith(staleWhileRevalidate(request));
    return;
  }

  // All other same-origin assets: cache-first (they're pre-cached and versioned)
  if (url.origin === self.location.origin) {
    event.respondWith(cacheFirst(request));
    return;
  }
});

// Network-first: try network, update cache, fall back to cache then offline page
async function networkFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const response = await fetch(request);
    cache.put(request, response.clone());
    return response;
  } catch (e) {
    return (await cache.match(request)) || (await cache.match('/offline.html'));
  }
}

// Cache-first: serve from cache instantly, only hit network if not cached
async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  try {
    const cache = await caches.open(CACHE_NAME);
    const response = await fetch(request);
    cache.put(request, response.clone());
    return response;
  } catch (e) {
    return new Response('Offline', { status: 503 });
  }
}

// Stale-while-revalidate: serve cache immediately, update in background
async function staleWhileRevalidate(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);

  const fetchPromise = fetch(request).then((response) => {
    cache.put(request, response.clone());
    return response;
  }).catch(() => null);

  return cached || (await fetchPromise) || new Response('Offline', { status: 503 });
}
