const levelNames = [
  "Intro", 
  "Classic ~ 1", 
  "Flying For Coins ~ 2",
  "Bouncy House ~ 3", 
  "Booby Trap ~ 4", 
  "Staircase of Doom ~ 5",
  "Boucin' Around ~ 6", 
  "Look Out Below ~ 7", 
  "Whoop de doo ~ 8",
  "Red Panda Panic ~ 9", 
  "Jumping to Infinity ~ 10", 
  "Cheese Grater ~ 11",
  "What Goes Up ~ 12", 
  "Onion Peeler ~ 13", 
  "No Shot ~ 14",
  "Leaps of Faith ~ 15", 
  "Wall Jumper ~ 16", 
  "Pipe Dream ~ 17",
  "Get a Rise ~ 18", 
  "Spring Into Action ~ 19", 
  "Waterpark ~ 20",
  "Long Way Down ~ 21", 
  "Grassy Fields ~ 22", 
  "Extreme Hops ~ 23",
  "WATER! ~ 24", 
  "Aquatic Adventure ~ 25", 
  "Watery Fun ~ 26",
  "Pure Water ~ 27", 
  "Skinny Trees ~ 28", 
  "In the Sky ~ 29",
  "The End ~ 30", 
  "Thanks to ~ 31", 
  "You ~ 32", 
  "Bonus ~ 33",
  "Bonus 2 ~ 34", 
  "Bonus 3 ~ 35", 
  "Parkour Master ~ 36",
  "One More Level ~ 37", 
  "Just one more... ~ 38", 
  "Ok fine this is the last one ~ 39"
];

export default levelNames;