 //loadLevels()
 const LEVELS = [
  //intro
  [
    '     = =                                         =',
    '     = =                                        =',
    '                                                =',
    '     ===                                              =',
    '    =   =                                          =',
    '                                                        =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=         l }  $$$      G ^      l     $$      }       O=',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==',

  ],
  //Classic
  [
    '	=                      ',
    '       ^^               ',
    '=                                                          ^^                ',
    '=                                                      x`xx`x^^              ',
    '=                                                                            ',
    '=                               l$                                        ',
    '=                              ==      !                   =                  ',
    '=                            $                             =         ',
    '=                         ==  ^^                          ==          -',
    '=                    l $                                  ==$         =     l$ ',
    '=              $    ===  ^                      $      =ll= =              ===',
    '=     $     } l                                       =????        l    $    ',
    '=  l  ^    === x`x   x`xx`xx`xx`xx`x       ^      ^  =     ? $   O=x`x^ =    ',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx??xx+xxxx+xx==.        ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    'x`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`x  x`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`x^',
    '','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',
    '                                                        QQQQ'
  ],
  //Flying for Coins
  [
    "=                          ",
    "=         ^    ^           ",
    "=                          ",
    "=                          ",
    "=    $    $    $    $     $",
    "=    $    $    $    $     $",
    "=                          ",
    "=         l                ",
    "=                l         ",
    "=                          ",
    "=                          ",
    "=     }      ^       l   O",
    "xx+xxxx+xxxx+xxxx+xxxx+xx==",
    "                           ",
    "                           ",
    "                           ",
    " x`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`x^^",
  ],
  //Bouncy house
  [

    '=                 ==  ==    ',
    '=                =      =    ',
    '=               =        =    ',
    '=              =          =    ',
    '=             =            =    ',
    '=            =              =    ',
    '=           =                =    ',
    '=          =                  =   ',
    '=   }     =                    =  ',
    'xx+xxxx+xx                      =',
    '         =                      =',
    '         =                      =',
    '         =                      =$',
    '         =       $       $      =$',
    '         =   lllllllllllllllll  =$',
    '         =   =  =  = ^ =  =  =  =',
    '         =                      =',
    '         =                      =',
    '         =$$$$$$$$$$   S$$$$$$$O=',
    '         llllllllllllllllllllllll',
    '         ',
    '         ',
    '         ',
    '         ',
    '         ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Booby trap
  [
    '=x`xx`xx`xx`xx`xx`xx`x^=',
    '=                      =',
    '=                      =',
    '=                      =',
    '=    $                 =',
    '=    l       $         =',
    '=   =O= } $  ^     $$ O=',
    'xx+xxxx+xxxx+xxxx+xx====',

  ],
  //Staircase of doom
  [
    'xx+xxxx+xxxx+xxxx+xxxx+xx====',
    '=                           =',
    '=                           =',
    '=                           =',
    '=                           =',
    '=         !                 =',
    '=    l                      =',
    '=   l                       =',
    '=  l   $                    =',
    '= l                         =',
    '=lx`xx`x^$$$$$$ }   $$$$x`xO=',
    'xx+xxxx+xxxx+xxxx+xxxx+xx====',

  ],
  //Bouncing Around
  [
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=     $    =',
    '=     =    =',
    '=         $=',
    '=     ^   ==',
    '= $l       =',
    '= =      l =',
    '=x`x^    $ =',
    '=x`x^      =',
    '=      $  O=',
    'xx+xx^^==ll=',
    '',
    '',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Look out Below
  [
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=          }              ',
    '=          =              ',
    '=          =   !          ',
    '=   lllllll=              ',
    '=     ^    =              ',
    '=     =    =              ',
    '=          =              ',
    '=          =              ',
    '=          =              ',
    '=   $$$$$  =              ',
    'llllllllllll     ^^   ^^ O',
    '              xx+xxxx+xx==',
    '                          ',
    'x`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`x^',
  ],
  //Whoop de doo
  [
    '=',
    '=',
    '=',
    '=',
    '=',
    '=                                                               $',
    '=',
    '=                  $           !',
    '=                  k                                            }',
    '=                  =                                            =x`xx`x',
    '=      x`x^',
    '=        =',
    '=        $     $              D',
    '=              =              D                             $              ===O',
    '=                             D                             l',
    '=                             D',
    '=$              $   $         D    $         $',
    '===llllllllllxx+xx====x`xx`xx`x=x`xx`xx`xxx+xx',
    '',
    '',
    '',
    '                                                        l',
    '',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Healthy Hurdles
  [
    '=                                              O             ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=          =                                                 ',
    '=          =                                   l             ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=          =                                                 ',
    '=          =                                   l             ',
    '=          =                                   =             ',
    '=      ^   =x`xx`xx`xx`xx`xx`xx`xx`x^^                    ',
    '=                                                            ',
    '=          =                             $                   ',
    '=          ==                            l                   ',
    '=      $       $       $       $         =                   ',
    '=                                                            ',
    '=  l   l } l   l   l   l   l   l   l   l                     ',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx                     ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    'x`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`x',
  ],
  //Onion can Fly
  [
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =     !',
    '=                                                 $         =',
    '=                                                 l         =',
    '=                                                           =',
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=                                               $           =',
    '=               $                               l           =',
    '=               l                                          l=',
    '=                                                           =',
    '=                    l         l         l                  =',
    '=                                                           =',
    '=          $                                                =',
    '=          l                                                =',
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=    $                                                     $=',
    '=  } l  x`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`x^^ l=       $  }   ^       $     ^    }   $   ^    $    O',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Free fallin'
  [
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=            l',
    '=',
    '=                        !',
    '=',
    '=',
    '=            l',
    '=',
    '=',
    '=',
    '=            $',
    '=            l',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=            l',
    '=',
    '=',
    '=',
    '=                        $             $      $    }  $           $           $    $ }          $        $           ',
    '=      }  lx`xx`xx`xx`xllllllx`xx`x^llllllllllllllllllllllx`xx`x^^llx`xx`xllllllllllllllx`xx`x^^llx`xx`x^llx`xx`x^llO',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Da brick wall
  [
    "===                                          =  =  =    O",
    "===                               $   ==l",
    "===                                l      ",
    "===            $}                  =      ",
    "===            ==            $  l         ",
    "===                     $    =            ",
    "===                   llll                ",
    "===          $                            ",
    "xx+xx==     ==                            ",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Leap O' Faith
  [
    "xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==",
    "=                  x`xx`xx`x                                  ",
    "=                                                                                     } ",
    "=                                                                                xx+xxxx+xx==",
    "=                   l                        }   ===           ===^^            x`xx`xx`x^",
    "=                                            ==        ll                                        ",
    "=                                         l                                 =                    =",
    "=        =                                                                $                                    !",
    "=                 =                                                       ===",
    "= }  $$             xx+xx=           lll",
    "xx+xx===                                                                                                       O",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Descending Tomfoolery
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=     $    $         $         $     }",
    "=     =    =         =         =     =",
    "^^==x`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`x=",
    "        ",
    "                                     !",
    "                                      ",
    "                    !       =        $",
    "                               x`x^",
    "                               ====  =",
    "                    $             ^  ^",
    "                               ",
    "                                     ",
    "                    $              ==",
    "                 ",
    "                    =         x`xx`xx`xx`xx`x^^",
    "",
    "                                     ",
    "                x`x ! x`x     l    l",
    "",
    "                                       O",
    "                    =                   ",
    "                          =      =    =",
    "",
    "",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Now this is hard
  [
    "=",
    "=",
    "=",
    "=                                                                                                   O",
    "=                             ",
    "=                             ",
    "=                             ",
    "=                               $    =^^                                                       =",
    "=                               =x`x^",
    "=                             ",
    "=                          =^^             l     $   ",
    "=                                              ^^==^^                                        ll",
    "=                             ",
    "=                                                           } ",
    "=                                                        xx+xx=            }  $",
    "=                                                             x`xx`xx`x^^xx+xx=  ",
    "=   }  $               $                                                      x`xx`xx`x^^====ll",
    "xx+xxxx+xx           lll                                   ",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //DON'T GET SPIKED
  [
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                             ",
    "=                             ",
    "=                             ",
    "=                  }                                            $           ",
    "=                 ===            $     $                  $      ",
    "=                              xx+xxxx+xx                 == ",
    "=        l   $$          ",
    "=        $                                        !",
    "=           x`xx`x            ",
    "=                                                 l                    $",
    "=",
    "=",
    "=       l $                                         $                  O",
    "xx+xxxx+xxxx+xx                                   l                   ===",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  



  ],
  //Platform Chaos
  [
    '=         ^             ^^',
    '=         =             ==',
    '=         =             ==                              =',
    '=         =         k- ^==^                             =',
    '=       $ =      $ xx+xx====              !             =',
    '=        ^=             $         ^                     =',
    '=        ==             $         =                     =',
    '=                                 =                     =',
    '=                       =   l     =                     =',
    '=                                 =                    =',
    '=                   lll^          =                     =',
    '=                   xx+xx         =                     =',
    '=                   D $$=         =                     =',
    '=                   D $$=         =       !             =',
    '=                  xx+xx=lll      =                     =',
    '=                                 =                     =',
    '=                                 =                     =',
    '=                                 =              O      =',
    '=                   ===           =                     =',
    '= } x`xx`x^=x`xx`xx`xx`xx`xx`xx`x^=x`x^^   }            =',
    'xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==',

  ],
  //Enter the Secret Lair
  [
    "=                                                                          O ",
    "=                             ",
    "=                                                              $  ",
    "=                                                             ===",
    "=                                                                               ",
    "=                      ",
    "=                  $              ",
    "=                             $   -   k                    l",
    "=                                ====         $  }         $",
    "= $  $   $    }                                xx+xx",
    "xx+xxxx+xxxx+xx=                                           = ",
    "=              D        }",
    "=  $     $ }   D        l",
    "xx+xxxx+xxxx+xx=    ",
    "=",    
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
  //Secret Lair
  [
    "=iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    "=",
    "=",
    "=",
    "=",
    "=                                                 ",
    "=                                                            D",
    "=                                                            D",
    "=                                                            D",
    "=                                                            D",
    "=                     }                $             $       D",
    "=         x`xx`x^     xx+xx=x`x^====^^====x`x^====^^====^^====",
    "=                    ==                                       =",
    "=                   ==                                        =",
    "=                                                             =",
    "=   lll $llllll               $             $               DDD=",
    "=                  }   llllll===lllll=lllll===llllll=lllll=lDOD=",
    "=                  xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx===D",
    "=          ",
    "=          =          $                    $                ",
    "=                    }",
    "=                DDD===        $           =              =  ",
    "=                D    ==^^=x`xx`x^=x`xx`xx`xx`xx`xx`x=x`xx`x^",
    "xx+xx=x`xx`xx`x^^      xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx=",
    "                   l   x`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`xx`x^^",
    "                   k",
    "                                                            ",
    "                                                                  =",
    "                                                            ",
    "                                                            ",
    "                      =      =x`xlllll==llllll=x`xx`x^^====        ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  

  ],
  //Rollercoaster
  [
    "=iiiiiiiiiiiii             =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=        ^                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",             
    "=  $  =  =                 =",
    "=     =  =                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=  $  =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",             
    "=     =  =                 =",
    "=     =  =                 =",
    "=  $  = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=   $ = $=                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=     =  =                 =",
    "= $   = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=   <<=  =                 =",             
    "=  ==== l=  <<<<<<<<<<<<<<<=",
    "=     = $=                 =",             
    "=     =  =                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=        =                 =",             
    "=        =                 =",
    "=>>>>>>>l=OOOOOOOOOOOOOOOOO=",
    "xx+xxxx+xxxx+xxxx+xxxx+xx===",
  ],
  //Onion's got HOPS
  [
    
    "=",
    "=                                                         O                        ",
    "=                                                                     {",
    "=                                                                     =",        
    "=",
    "=",
    "=                                   $                                        {",
    "=                                                                            l",
    "=   }        $",
    "=^=^=^=^=x`x^                                                           $",
    "=                    !          =x`xx`xx`x  x`xx`xx`xx`xx`x^^",
    "=                           ^^==                         =                 $",
    "=                      $                                  $                ",
    "=          x`xx`xx`x^=                                                    l",
    "=                                          $$$}                     $",
    "=                                         xx+xx          l  ====x`xx`xx`x^",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Cruisin' for a Bruisin'
  [
    
    "= ",
    "=",
    "=",
    "=",
    "=",
    "=                                     $ l  ",
    "=      =x`xx`xx`x^                    =                !",
    "=     =                     ^",
    "=    =",
    "=    =",
    "=   =",
    "=   =                       l",
    "= ! = $  }",
    "=   =    ===",
    "=   =         =             ",
    "=                          l",
    "=",
    "=                     -",
    "=                     l  ^",
    "=",
    "=",
    "=                         l",
    "=",
    "=",
    "=                          ^   l",
    "=",
    "=                            l",
    "=",
    "=                          $  ",
    "=",
    "=$         $               l",
    "=     $",
    "=              $",
    "=   $    $           $                               OOOOO",
    "xx+xxxx+xxxx+xxxx+xx====iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixx+xxiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Mount Scallion
  [
    "=                                                                                                 =   =x`xx`xx`x$",
    "=                                                                                                =               =  =x`x",
    "=                                                                                                                      =^",
    "=                                                                                               x`x^^=                  =^",
    "=                                                                                             =                          =^",
    "=                                                                                           ^=        x`xx`x^      =^     =^",
    "=                                                                                          ^=                              =^",
    "=                                                                                          =                                =^",
    "=                                                                                         =                  $-$             =^",
    "=                                                                                         ^                  ===              =^",
    "=                                                                                         ^ x`xx`x^==      ^^   ^^ !      ==   =^",
    "=                                                                                         ^                                     =^",
    "=                                                                                         ^                                      =^",
    "=                                                                                        $^         l                 ^^=         =^",
    "=                                                                                        l^        $     $    $                    =^",
    "=                                                                                         ^     xx+xxxx+xxxx+xxxx+xx                =x`xx`xx`x",
    "=                                                                                         ^",
    "=                                                     x`xx`xx`xx`x                  $x`xx`x                          O",
    "=                                                     xx+xxxx+xx==           x`xx`x^=",
    "=                                                     x`xx`xx`xx`x          =",
    "=                                                                       ^  ^",
    "=                      $                               $$         $",
    "=                      =                              xx+xx====  ==",
    "=                      ^                              ^",
    "=                      ^                              ^",
    "=                      ^                              ^           }      lx`xx`xx`xx`xx`xx`xx`xx`x^^",
    "=                     ^                              ^       x`x^==",
    "=                     ^                              ^",
    "=          $     $    ^             $$$$$$$          ^",
    "xx+xx===x`xx`xx`x^l   ^            xx+xx====      l",
    "",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //DROP
  [
    "=",
    "=",
    "=                    $",
    "=               $",
    "=",
    "=",
    "= =  =  =       =    =",
    "=                                               k",
    "=                                           ^^    ^^",
    "=     =                                     ^      ^",
    "=$     }          $                         ^   = ^^",
    "xx+xx====x`xx`x^^                      l",
    "=                                             $$ }",
    "=                   }                       xx+xx= ",
    "=               xx+xx",
    "=                                $      =                {",
    "=                     x`xx`xx`x^^=x`xx`xx`x^^            = ",
    "=                         ",
    "=",
    "=",
    "=                                                $ ",
    "=                                                 }",
    "=                                              =  =  ",
    "=                                               ^^",
    "=",
    "=",
    "=                            ",
    "=                                  ^             }    $       ^       }",
    "=                            =  =     =     =    =    =     =   =     =   =   =  =  =",
    "=                                                                                =  =",
    "=                                                                                =$ =   ",
    "=                                                                                =  =",
    "=                                                                                =  =",
    "=                                                                               DDDDDD",
    "=              ",
    "=                                                                                 O ",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Tower of Pain
  [
    "=",
    "=",
    "=    ^                    $$                            k",
    "=    = }       x`x===  x`xx`x^^     }                  ===",
    "=    ===       xx+xxxx+xxxx+xxxx+xx==",
    "=    =         =                   D",
    "=    =         =  !                D         }",
    "=    =    ^    =                   D      llll",            
    "=    xx+xx=    =      ^  ^         D",
    "=    $$=      ^=     llllllllllxx+xx==",
    "=      =     ===               =",
    "=      =       =             O =",
    "=      =  ^  ^ =            ====",
    "=      =  llll xx+xx==         =",
    "=      =       =               =",
    "=      =       =             $$=",
    "=      =       =x`xx`xx`xx`x====",
    "=      =       xx+xxxx+xxxx+xx==",
    "=      =    ^===               =",
    "=      =    ==                 =",
    "=                              =",
    "=    }                     $$$ =",
    "xx+xxxx+xxxx+xx=           ===",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Tricky timing
  [
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=     }                                     ",
    "xx+xxxx+xxD               =                      ",
    "=$$$$$$$$$D                            ",
    "=$$$$$$$$$D                                 ",
    "xx+xxxx+xxD                                     ",
    "=  x`xx`xx`xx`xx`xx`x^  x`xx`x^^    }          ",
    "=                     ll           ==             !",
    "=           =                          ",
    "=            $                 $       ",
    "=                             ==      ",
    "=           k                                   DDDDD",
    "=           l         =                         D O D",
    "=                                               D = D",
    "iiiiiiiiiiiiii^^==^^iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Insane Precision
  [
    "", //don't make this easier
    "                          ^^   x`x",
    "=                           $",
    "=",
    "=                        D",
    "=                        D   k  ",
    "=                        D",
    "=                     !  D",
    "=                        D     l",
    "=                        D     $",
    "=                     D  D x`x   x`x^^",
    "=$ }           ^     DOD       ", 
    "xx+xxx`xx`x^^  =x`x^^===",
    "              $                l",
    "                        $",
    "                        =",
    "               }",
    "               ==",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //It's Not That Simple
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=                   ",
    "=",
    "=",
    "=                                                                     k",
    "=",
    "=            }                                      $",
    "=      $   xx+xx                              ^     l                ^",
    "=          =   =",
    "=          i O =            $                            =",
    "= $        i   =x`xx`xx`xx`x=x`xx`xx`x^  x`x^                       }", 
    "xx+xxxx+xxxx+xx=                D      $       l                    l",
    "           =                    D",
    "           = O                  D",
    "           xx+xxxx+xxxx+xx==    =   ==^==     ===              =",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    ],
  //It's a long Drop
  [
  "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=", "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=", "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=",
    
    "=                                         ^^",//haha its a long fall
    "=                               l        ====",
    "=                       ^                                               O",
    "=                       ==                               ====           =",
    "xx+xxxx+xx       ^^  x`x    ",
    "",
    "                      }",
    "                    ===   =",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Into the Abyss
  [
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=   -    =",
    "=  ===  = ",
    "=$  =$  =",
    "= ! =$! =",
    "=  $=$  =",
    "= $ =$  =",
    "=$  =$  =",
    "= $ =$  =",
    "=  $=$  =",
    "= $ =$  =",
    "=^  =$  =",
    "=$  =$  =",
    "=$  =$  =",
    "=$  =$  =",
    "=^  =$  =",
    "=$  =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =   =",
    "=   =$  =",
    "=   = $ =",
    "=   =  $=",
    "=   =  $=",
    "=   =$  =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =  $=",
    "=   = $ =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   =$  =",
    "=   = $ =",
    "=   =$  =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =x`x=",
    "=^O^=^O^=",
    "xx+xx====",
    
    
  ],
  //Enter the labyrinth
  [
    "=   xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx====",
    "=                                                                                                     =",
    "=   =                                                                                                 =",
    "=   =                                                                                                 =",
    "=   =                                                      $                                        k =",
    "=   =                                                                                              ====",
    "=   =                                                      xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx====",
    "=   =                                                      =                                          =",
    "=   =                                                      =                                          =",
    "=   =                                                      =                                          =",
    "=   =                                                      =                                        O =",
    "=   =                                                      =                         $             ====",
    "=                                                          =     =                 xx+xx====x`xx`xx`x^^",//hardest
    "=   =                                                      =     =                     =", //possible
    "=   xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==        =     =                     =",//jump :)
    "=   ^                              =              =        =  $  =                     =",
    "=                    }   ^         =       x`x^^  xx+xxxx+xxxx+xx====                  =",
    "=                $   =   =         =       xx+xx                    =         l        =",
    "=                ^   =          =  $  ^                             =x`xx`xx`x=        =",
    "=                =   =          =     =                             xx+xxxx+xx====l    =",
    "=      x`xx`x^   =   =x`x=x`xx`x=  lll=^  }   ^^       ^  ^         =            $     =",
    "=llxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==llllllllllllll==                     =",
    "                                                               =                       =",
    "                                                               =   }         ===       =",
    "                                                               xx+xx=x`xx`xx`xx`xx`xx`x=",
    "                                                                    xx+xxxx+xxxx+xxxx+xx",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    
  ],
  //The Labyrinth
  [
  "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  "i                                                           i",
  "i                                                           i",
  "i                                                           i",
  "i                                                           i",
  "xx+xxxx+xxxx+xxxx+xxxx+xx==  xx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==",
  "=     =                 =                 =        =     =  =",//MAZE TIME! you can jump infinitely in this level,
  "=     =                 =           -   $ =        =     =  =",//someone do that or I will when im done
  "=        xx+xxxx+xx===  xx+xxxx+xx  =  ====  =  =  =  =  =  =",
  "=  =     =        =  =           =  =  =     =  =     =     =",
  "=  =     =        =  =           =  =  =     =  =     =     =",
  "=  =  ====  ====  =  xx+xxxx+xx  =  ====  ====  xx+xxxx+xx  =",
  "=  =  =        =  =        =  =  =  =     =  =  =     =     =",
  "=  =  =        =  =        =  =  =  =     =  =  =     =     =",
  "=  ====  xx+xx==  ====  =  =  =  =  =  ====  =  =  =  ====  =",
  "=     =  =  =     =     =     =  =  =  =     =  =  =     =  =",
  "=     =  =  =     =     =     =  =  =  =     =  =  =     =  =",
  "====  =  =  =  ====  xx+xxxx+xx  =  =  =  ====  =  ====  =  =",
  "=     =     =  =     =           =     =  =     =     =  =  =",
  "=     =     =  =     =           =     =  =     =     =  =  =",
  "=  ====  ====  =  =  =  xx+xxxx+xx  ====  =  ====  ====  =  =",
  "=        =     =  =        =     =        =        =     =  =",
  "=        =     =  =        =     =        =        =     =  =",
  "=  xx+xx==  xx+xxxx+xx===  =  =  xx+xxxx+xx  xx+xx==  ====  =",
  "=  =        =     =     =     =           =  =     =     =  =",
  "=  =        =     =     =     =   G       =  =     =     =  =",
  "=  =  ====  =  =  =  =  xx+xxxx+xxxx+xx=  ====  =  ====  =  =",
  "=  =  =     =  =     =     =        =           =        =  =",
  "=  =  =     =  =     =     =        =           =        =$$=",
  "=  =  ====  =  xx+xxxx+xx  ====  =  =  xx+xxxx+xxxx+xxxx+xx==",
  "=  =     =  =  =        =     =  =  =  =  =           =     =",
  "=  =     =  =  =        =     =  =  =  =  =           =     =",
  "=  ====  ====  =  ====  ====  =  ====  =  =  xx+xx==  =  =  =",
  "=     =     =  =  =        =  =  =     =  =     =  =     =  =",
  "=     =     =  =  =        =  =  =     =  =     =  =     =  =",
  "====  ====  =  ====  ====  =  =  =  ====  ====  =  xx+xx==  =",
  "=  =     =  =        =     =  =        =     =        =     =",
  "=  =     =  =        =     =  =        =     =        =     =",
  "=  ====  =  xx+xxxx+xx  ====  xx+xx==  =  =  xx+xx==  =  ====",
  "=     =  =  =        =     =     =  =  =  =     =     =     =",
  "=     =  =  =        =     =     =  =  =  =   G =     =     =",
  "=  =  =  =  =  =  xx+xx==  ====  =  =  ====  ====  xx+xx==  =",
  "=  =     =  =  =  =        =     =  =  =     =     =        =",
  "=  =     =  =  =  =        =     =  =  =     =     =        =",
  "=  xx+xx==  =  =  =  xx+xx==  ====  =  =  ====  ====  ====  =",
  "=  =     =     =     =  =     =     =  =     =  =  =  =  =  =",
  "=  =     =     =     =  =     =     =  =     =  =  =  =  =  =",
  "=  ====  xx+xxxx+xx===  =  xx+xx==  =  ====  =  =  =  =  =  =",
  "=              =        =  =     =        =  =     =  =     =",
  "=        G     =        =  =     =        =  =     =  =     =",
  "xx+xxxx+xx===  ====  =  =  =  =  xx+xx==  =  ====  =  =  ====",
  "=  =                 =  =     =     =        =     =  =  =  =",
  "=  =                 =  =     =     =        =     =  =  =  =",
  "=  =  xx+xxxx+xxxx+xxxx+xxxx+xx===  xx+xxxx+xx  ====  =  =  =",
  "=     =  =              =        =              =  =  =     =",
  "=     =  =              =        =              =  =  =     =",
  "=  ====  =  xx+xxxx+xx  =  ====  =  xx+xxxx+xx===  =  ====  =",
  "=        =           =     =  =  =                 =  =     =",
  "=        =           =     =  =  =                 =  =     =",
  "xx+xx==  xx+xxxx+xx  xx+xx==  =  xx+xxxx+xxxx+xx====  xx+xx==",
  "=     =           =  =     =                       =        =",
  "=     =           =  =     =             G         =        =",
  "=  xx+xxxx+xx===  =  =  =  xx+xxxx+xxxx+xxxx+xx==  xx+xx==  =",
  "=                 =     =        =                          =",
  "=             k   =     =        =                          =",
  "xx+xxxx+xxxx+xxxx+xxxx+xx====DDDxx+xxxx+xxxx+xxxx+xxxx+xx===",
  "                              ",
  "                              O  ",
  "",
  "",
  "iiiiiiiiiiiiiiiiiiiiiiiiiiiii i iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
  //Onion's Demise
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=                       x`x    O",
    "=                xx+xxxx+xxxx+xx",
    "=                = = = = = = = =",
    "=                xx+xxxx+xxxx+xx",
    "=                = = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "=               lxx+xxxx+xxxx+xx",
    "=               l= = = = = = = =",
    "xx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  // the heist (made is level designer)
[
  '=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                   =     =                                     ',
'=                   =G   G=                                     ',
'=                   =DDDDD=                                     ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                    D$$D        ^                              ',
'=                    D$$D        ^                              ',
'=            $       D$$D        ^                              ',
'=                    D$$D        ^                              ',
'=                    DDDD        ^                              ',
'=                                ^                              ',
'=                               O^                              ',
'=      $     l     =  Gk   =     ^                              ',
'xx+xxxx+xx=== ====^xx+xxxx+xx====^                              ',
'                                                                ',
],

	//We're Just Getting Started
[
	"     =",
	"     =",
	"     xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx",
	"       =                                         =     =        =",
	"       =                                         =     =        =",
	"                        ===     ^  ===   ===  ^                 =",
	"                  ^^    = ===   ====          =     ^     ^     =",
	"          ^  ^    ==    =       =             =     =     =     =",
	"     ^  llllllll  ==    =x`xx`x^=x`xx`xx`xx`x^=  ^  =  ^  =     =",
	"xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==lllllllllllll OO =",
],
	[
	"=    xx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==",
	"=    =                     =  =      ",
	"=    =    k                =  =      ",
	"=    =   xx+xx====  v      =O        ",
	"=    =   vv                =         ",
	"=    =                     =         ",
	"=    =                     =x`xx`x   ",
	"=    =              l      xx+xx===  ",
	"=    =   ^                 D         ",
	"=    =   =ll=              D         ",
	"=                          xx+xx===  ",
	"=                          =         ",
	"=        x`xx`xx`xx`xx`xx`x=x`xx`xx`x",
	"xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx==",
		],
	[
"=   = O             =",
"=   =               =",
"=   xx+xx           =",
"=   = k =           =",
"=   =   =       D   =",
"=   =   =       D   =",
"=   =   =       xx+xx",
"=   ==  =           =",
"=   =               =",
"=   =               =",
"=   xx+xx===        =",
"=   =               =",
"=   =               =",
"=   =              ==",
"=                  ==",
"=                ^^==",
"xx+xxxx+xxxx+xxxx+xx=",
		],
	[
"xx+xxxx+xx=   OO   =",
"=         =   vv   =",
"=         =        =",
"=    ^^  ^=        =",
"xx+xx==  ==        =",
"=    $=  D=x`x     =",
"=    $=  D====ll   =",
"=   ===  D         =",
"=        D         =",
"=        D         =",
"=k  x`x  D  ^^  x`x=",
"xx+xxxx+xxxx+xxxx+xx",

		],
	[
"=  =            ^  x`x  x`x^^  ^^",
"=  =            xx+xxxx+xx===  ==",
"=  =            =               =",
"=  =     =      =               =",
"=  =            =   ^^          =",
"=  =            =  =ll===       =",
"=  =            =       =       =",
"=  =         =  =       =       =",
"=  =vv=      =  =   ^^  =^^  x`x=",
"=  =     xx+xxxx+xx===  xx+xxxx+xx",
"=  =     =",
"=  =     =            OO",
"=  =lll===",
"=  =     =",
"=  =     =",
"=      = =",
"=      = =",
"xx+xxxx+xx",


		],
	//Freaky Deeky
	//Eli, if you even touch this level, I will doxx you and your family, call up my uncle and tell him to barrage you with so many scam calls that you will never have a moment of peace ever again. Comprende amigo?
[
"i    G                    iiiiii                                                   i",
"i                                                                                  i",
"i^      ^        h                                                                  i",
"ixx+xx===  ^^== ===??===    ==  === = ===????===   =^=^==   xx+xx   = =  ====  i",
"i   v  v               hh  ll                i i                                  i",
"i                        ?                                                         i",
"i                                                                                  i",
"i                                                                                  i",
"i      ==??==      hh    ==l====       xx+xx??                                i",
"i        ii        ll                      ^^                                        i",
"i                                                                                  i",
"i                            ^       G^                                             i",
"i   ==?===    i==??===   i   xx+xxi====iiii   =i====  l ==?== ? l ===l ===  ====   i",
"i       i                                                                         i",
"i                                                                                  i",
"i                                                                                  i",
"i                                                                                  i",
"iii????hh      ii??i       ii?===h?ii         ii===h=ii      i???ii         ii??ii",
"i                                                                                  i",
"$   xx+xx                              ^     l                ^                    i",
"=          =   =                                                                   i",
"=          i  =            $                            =                          i",
"=hh       i   =x`xx`xx`xx`x=x`xx`xx`x^  x`x^                                       i", 
"                                                                                   i",
"     ==?==                h      $       l                    l                    i",
"                                                                                   i",
"i                                                                                  i",
"i ^         =     h               h                                                i",
"i                                                                                  i",
"           =             h      h                                                  i",
"i                                                                                  i",
"           ===??===hxx+xx==    =   ==^==     ===              =                    i",                             
"i                                                                                  i",
"i  ==??=  =h=  == ==??==   =?=  ==?=^     ^==??= ==i  ===   == ==??==   ==??=    = i",
"",
"====  =  ====  ====    ====  =  =  xx+xx==  = i  ==                                i",
"",
"",
  "=     ?     ?  =  =        i  =  ?     ?  =     =  h     =  =                     i",
"",
"",
  "?     =     i  =  ? h      ?  =  i     h  =     ?  =     =  =                     i",
"",
"",
  "====  ====  =  ==h===  =  =  =  ====  ====  ?  ===h===  =                     i",
"",
  "=  =     =  =        =     i  =            i                                     i",
"                                                                                    i",
"i   ==i??==  =??xx+xx  ??  xx+xx ^ = ^ =  =  ==??==   xx+xx ====  ==i==  ===??===ii i",
"",
"                        ===     ^  ===   ===  ^                 =",
"",
"",
	"                  ^^    = ===   ====          =     h     i     =",
"",
"",
	"          ^  ^    ==    =       =             ?     =     =     =",
"",
"",
"        ^   G   ^                                                    iiiiiiiiiiii===i ",
"i       ===hh===  ====        ==??=        =??==        ===                         i",
"                                                                                    O",
"i    ^     l    x`x^lllllx`x ^ ^^l^ ^ ^ l ^ l ^ l ^     ^ h ^                            i",
"i                                                                                 h      i",
"i                                                                                  iiiiiii",
"i                      v      l                                                    i",
"i                  ^v^v^v^v^v           G                    v   v                 i",
"i====   ==  i===i =  ==  =  =  ===  ^xx+xx==^ == ^ ??  ?=  ==  =  =  =??==  =  h   i",
"i     l                           l             l  ==          l         l         i",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
	//dodging and weaving
[
"=              =",
"=              =",
"=              =",
"=              =",
"=  $$$$        =",	
"=              =",
"xx+xxxx+xx=    =",
"          =  ^^=",
"          =    =",
"          = $$ =",
"          =    =",
"          =^^  =",
"          =    =",
"          = $$ =",
"          =   l=",
"          =    =",
"          =    =",
"          =^$$^=",
"          =^$$^=",
"          =^$$^=",
"          =OOOO=",
"          xx+xx",
],
	 [
"", //The Tube
"",
"       x`xx`xx`xx`xx`x^",
"===    xx+xxxx+xxxx+xx=   =        =",
"  =                       =        =",
"  ==                      =x`x  x`x=",
"       ===    ===    ==   =        =",
"                          =        =",
"                          =        =",
"                          =        =",
"                          = x`x    =",
"                          =^===  ^^=",
"                          =        =",
"                          =        =",
"                          =  ^^    =",
"                          =  xx+xx==",
"                          =        =",
"                          =        =",
"                          =    ^^  =",
"                          xx+xx==  =",
"xx+xxxx+xxxx+xxxx+xxxx+xx==     =  =",
"=           =                   =  =",
"=           =                      =",
"=  ^^  ^^   =  ^     ====   =      =",
"=  xx+xx==  =  =        =   =      =",
"=        =     =        =   =     ==",
"=        =     =        =   =     ==",
"=        =     =x`xx`x^^=x`x=x`x^^==",
"=^       =lllllxx+xxxx+xxxx+xxxx+xx=",
"xx+xx==  =",
"=        =",
"=        =",
"=    ^^  =",
"=  xx+xx==",
"=        =                                            iiiiiiiiii",
"=        =                                            i        i",
"=        =                                            i   OO   i",
"=        xx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xxxx+xx=DDDDDDDD=",
"=        =             =       =             =                 =",
"=        =             =       =             =                 =",
"=        =             =       =       ====  =   ====          =",
"=^^  x`x^=             xx+xx====       =     =   =             =",
"=            xx+xx==                  ==     =  ==           ===",
"=            = $$$ =                  =   ====  =              =",
"=            =                        =         =              =",
"=          ^^=          ^^   ^^       =         =              =",
"xx+xxxx+xx====llllllllllllllllllxx+xxxx+xxxx+xxxx+xx===        =",
"                                                      =x`x     =",
"                                                      xx+xx    =",
"                                                      =        =",
"                                                      =        =",
"                                                      =        =",
"                                                      =       ==",
"                                                      =       ==",
"                                                      =        =",
"                                                      =x`x     =",
"                                                      =vvv=    =",
"                                                      =        =",
"                                                      =        =",
"                                                      =        =",
"                                                      =      ===",
"                                                      =  ^  ^  =",
"                                                      =  =ll=  =",
"                                                      =        =",
"                                                      =      k =",
"                                                      =        =",
"                                                      xx+xxxx+xx",




		 ],
	 //Electric Boogaloo
	 [
"=                   ="	
"=                 ^ =",
"=               ^   =",
"=                   =",
"=                   =",
"=xx+xx====          =",
"=        x`x^^   l  =",
"=                   =",
"=                   =",
"=vvvvv    x`xx`xx`xl=",
"=                   =",
"=                   =",
"=   xx+xx           =",
"=kvvvvvvv           =",
"=             l     =",
"=                   =",
"=ll===              =",
"=    x`x   ll  ^    =",
"=                   ="
"=                   ="
"=      x`xx`xx`xx`x =",
"=                   =",
"=                   =",
"=   ===x`x^         =",
"=                   =",
"=         lx`x^^    =",
"=                   =",
"=l^^xx+xxxx+xx=     =",
"=                   =",
"=                   ="
"=                   ="
"=       xxxx&xxxxx`x=",
"=                   =",
"=xx+xx              =",
"=    ^              =",
"=    x`xx`x   x`xx`x=",
"=    ^              =",
"=       xx+xxxx+xx===",
"=                   =",
"=                   =",
"=          =  ^  ^  =",
"=          =  =ll=  =",
"=          =        =",
"=          DDDDDDDDDD",
"=          =        =",
"=          =        =",
"=          =        =",
"=          = ^   ^  =",
"=             =O=",
	 ],
	 [ //WAGHAHAHGHAHAGAGHAGHAHHHGHHHH
	 ' k=                                                             ',
'DD=                                                      = =DD= ',
'  =  D                                   D          =      =  = ',
'  =             D          D                               =OO= ',
'  =                                            D           ==== ',
'  =                   D             D                           ',
'  =D                                                   =        ',
'  =                                              D              ',
'  =           D                                                 ',
'  =                                D  D                         ',
'  =                  D       D                   D      =       ',
'  =   D                                                         ',
'  =                                                             ',
'  =                                                         D   ',
'  =          D         D                             =          ',
'  =                                           D                 ',
'  =                             D     D                         ',
'  =                                                     =       ',
'  =                                                             ',
'  =              D      D                                       ',
'  =         D                                                   ',
'  =                                     D                  =    ',
'  =     D                                                       ',
'  =                                                  =          ',
'  =D                                                            ',
'  =          D         D                                        ',
'  =                                  =        =       D         ',
'  =                                                             ',
'  =                           =                                 ',
'  =                                             D               ',
'  =   D                D                                        ',
'  =          D                                                  ',
'  =                               =                           D ',
'  =                                                             ',
'  =                                                             ',
'  =                             =                               ',
'  =  D        =                                                 ',
'                    =                                           ',
'                            =              D          D         ',
'                                                 D            D ',
'         =                                                      ',
'==                                                              ',
	 ],
  //end of level code 
]

const levelConf = {
  tileWidth: 64,
  tileHeight: 64,

  tiles:{
    "=": () => [
      sprite("grass"),
      area(),
      body({ isStatic: true }),
      scale(1),
      offscreen({ hide: true }),
      anchor("bot"),
      "ground"
    ],
    "+": () => [
      sprite("grass5"),
      area(new Rect(vec2(), 160, 32)),
      body({ isStatic: true }),
      offscreen({ hide: true, distance: 160 }),
      scale(1),
      anchor("bot"),
      "ground"
    ],
    "_": () => [
      sprite("grass25"),
      area(new Rect(vec2(), 800, 32)),
      body({ isStatic: true }),
      offscreen({ hide: true, distance: 800 }),
      scale(1),
      anchor("bot"),
      "ground"
    ],
    "?": () => [
      sprite("fake"),
      area(),
      scale(1),
      offscreen({ hide: true }),
      anchor("bot"),
      "ground"
    ],
    "$": () => [
      sprite("coin"),
      area(),
      offscreen({ hide: true }),
      anchor("bot"),
      "coin",
    ],
    "^": () => [
      sprite("spike"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true }),
      anchor("bot"),
      "danger",
    ],
    "`": () => [
      sprite("spike3"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true, distance: 96 }),
      anchor("bot"),
      "danger",
    ],
    "&": () => [
      sprite("spike9"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true, distance: 288 }),
      anchor("bot"),
      "danger",
    ],
    "v": () => [
      sprite("dspike"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true }),
      anchor("top"),
      "danger",
    ],
    "O": () => [
      sprite("portal"),
      area({ scale: 0.5, }),
      offscreen({ hide: true }),
      pos(0, -12),
      anchor("bot"),
      "portal",
    ],
    "l": () => [
      sprite("jumpy"),
      anchor("bot"),
      offscreen({ hide: true }),
      area(),
      "jumpy",
    ],
    "D": () => [
      sprite("door"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true }),
      anchor("bot"),
      "door",
    ],
    "k": () => [
      sprite("key"),
      offscreen({ hide: true }),
      area(),
      anchor("bot"),
      "key",
    ],
    ">": () => [
      sprite("coasterRight"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true }),
      anchor("bot"),
      "right",
    ],
    "<": () => [
      sprite("coasterLeft"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true }),
      anchor("bot"),
      "left",
    ],
    ".": () => [
      sprite("block"),
      area(),
      offscreen({ hide: true }),
      body({ isStatic: true }),
      anchor("bot"),
    ],
    "{": () => [
      sprite("signpostl"),
      area(),
      offscreen({ hide: true }),
      anchor("bot"), 
    ],
      "}": () => [
      sprite("signpostr"),
      area(),
      offscreen({ hide: true }),
      anchor("bot"), 
    ],
      "-": () => [
      sprite("signposte"),
      area(),
      offscreen({ hide: true }),
      anchor("bot"), 
    ],
      "i": () => [
      sprite("invisdanger"),
      offscreen({ hide: true }),
      area(),
      "danger",
      anchor("bot"), 
    ],
    "~": () => [
      sprite("invis25"),
      area(new Rect(vec2(), 800, 32)),
      offscreen({ hide: true, distance: 1 }),
      "danger",
      anchor("bot"), 
    ],
    "#": () => [
      rect(2400, 32),
      area(new Rect(vec2(), 2400, 32)),
      offscreen({ hide: true, distance: 1 }),
      "danger",
      anchor("bot"), 
      opacity(0),
    ],
    "S": () => [
      sprite("invisdanger"),
      area(),
      offscreen({ hide: true }),
      "spawn",
      anchor("bot"), 
    ],
    "Q": () => [
      sprite("invisdanger"),
      area(),
      offscreen({ hide: true }),
      "arg",
      anchor("bot"),
    ],
    "G": () => [
      sprite("ghost"),
      patrol(),
      offscreen({ hide: true }),
      "enemy",
      anchor("bot"),
      area(), 
      body(), 
      ],
    "!": () => [
      sprite("darrow"),
      anchor("bot"),
      offscreen({ hide: true }),
      area(),
    ],
  },
  
}
function patrol(speed = 60, dir = 1) {
	return {
		id: "patrol",
		require: [ "pos", "area", ],
		add() {
			this.on("collide", (obj, col) => {
				if (col.isLeft() || col.isRight()) {
					dir = -dir
				}
			})
		},
		update() {
			this.move(speed * dir, 0)
		},
	}
}

export { LEVELS, levelConf }
