 //loadLevels()
 const LEVELS = [
  //intro
  [
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=                                                       =',
    '=         l }  $$$      G ^      l     $$      }       O=',
    '=========================================================',

  ],
  //Classic
  [
    '	=                      ',
    '       ^^               ',
    '=                                                          ^^                ',
    '=                                                      ^^^^^^^^              ',
    '=                                                                            ',
    '=                               l$                                        ',
    '=                              ==      !                   =                  ',
    '=                            $                             =         ',
    '=                         ==  ^^                          ==          -',
    '=                    l $                                  ==$         =     l$ ',
    '=              $    ===  ^                      $      =ll= =              ===',
    '=     $     } l                                       =????        l    $    ',
    '=  l  ^    === ^^^   ^^^^^^^^^^^^^^^       ^      ^  =     ? $   O=^^^^ =    ',
    '=======================================================??============.        ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    '                                                                     ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii  iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii^',
    '','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',
    '                                                        QQQQ'
  ],
  //Flying for Coins
  [
    "=                          ",
    "=         ^    ^           ",
    "=                          ",
    "=                          ",
    "=    $    $    $    $     $",
    "=    $    $    $    $     $",
    "=                          ",
    "=         l                ",
    "=                l         ",
    "=                          ",
    "=                          ",
    "=     }      ^       l   O",
    "===========================",
    "                           ",
    "                           ",
    "                           ",
    " iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii^^",
  ],
  //Bouncy house
  [

    '=                 ==  ==    ',
    '=                =      =    ',
    '=               =        =    ',
    '=              =          =    ',
    '=             =            =    ',
    '=            =              =    ',
    '=           =                =    ',
    '=          =                  =   ',
    '=   }     =                    =  ',
    '==========                      =',
    '         =                      =',
    '         =                      =',
    '         =                      =$',
    '         =       $       $      =$',
    '         =   lllllllllllllllll  =$',
    '         =   =  =  = ^ =  =  =  =',
    '         =                      =',
    '         =                      =',
    '         =$$$$$$$$$$   S$$$$$$$O=',
    '         llllllllllllllllllllllll',
    '         ',
    '         ',
    '         ',
    '         ',
    '         ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Booby trap
  [
    '=iiiiiiiiiiiiiiiiiiiii^=',
    '=                      =',
    '=                      =',
    '=                      =',
    '=    $                 =',
    '=    l       $         =',
    '=   =O= } $  ^     $$ O=',
    '========================',

  ],
  //Staircase of doom
  [
    '=============================',
    '=                           =',
    '=                           =',
    '=                           =',
    '=                           =',
    '=         !                 =',
    '=    l                      =',
    '=   l                       =',
    '=  l   $                    =',
    '= l                         =',
    '=l^^^^^^^$$$$$$ }   $$$$^^^O=',
    '=============================',

  ],
  //Bouncing Around
  [
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=          =',
    '=     $    =',
    '=     =    =',
    '=         $=',
    '=     ^   ==',
    '= $l       =',
    '= =      l =',
    '=^^^^    $ =',
    '=^^^^      =',
    '=      $  O=',
    '=====^^==ll=',
    '',
    '',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Look out Below
  [
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=                         ',
    '=          }              ',
    '=          =              ',
    '=          =   !          ',
    '=   lllllll=              ',
    '=     ^    =              ',
    '=     =    =              ',
    '=          =              ',
    '=          =              ',
    '=          =              ',
    '=   $$$$$  =              ',
    'llllllllllll     ^^   ^^ O',
    '              ============',
    '                          ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii^',
  ],
  //Whoop de doo
  [
    '=',
    '=',
    '=',
    '=',
    '=',
    '=                                                               $',
    '=',
    '=                  $           !',
    '=                  k                                            }',
    '=                  =                                            =^^^^^^',
    '=      ^^^^',
    '=        =',
    '=        $     $              D',
    '=              =              D                             $              ===O',
    '=                             D                             l',
    '=                             D',
    '=$              $   $         D    $         $',
    '===llllllllll=========^^^^^^^^^=^^^^^^^^^=====',
    '',
    '',
    '',
    '                                                        l',
    '',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Healthy Hurdles
  [
    '=                                              O             ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=          =                                                 ',
    '=          =                                   l             ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=                                                            ',
    '=          =                                                 ',
    '=          =                                   l             ',
    '=          =                                   =             ',
    '=      ^   =^^^^^^^^^^^^^^^^^^^^^^^^^^^                    ',
    '=                                                            ',
    '=          =                             $                   ',
    '=          ==                            l                   ',
    '=      $       $       $       $         =                   ',
    '=                                                            ',
    '=  l   l } l   l   l   l   l   l   l   l                     ',
    '========================================                     ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Onion can Fly
  [
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =     !',
    '=                                                 $         =',
    '=                                                 l         =',
    '=                                                           =',
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=                                               $           =',
    '=               $                               l           =',
    '=               l                                          l=',
    '=                                                           =',
    '=                    l         l         l                  =',
    '=                                                           =',
    '=          $                                                =',
    '=          l                                                =',
    '=                                                          l=',
    '=                                                           =',
    '=                                                           =',
    '=                                                           =',
    '=    $                                                     $=',
    '=  } l  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ l=       $  }   ^       $     ^    }   $   ^    $    O',
    '================================================================================================================',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Free fallin'
  [
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=            l',
    '=',
    '=                        !',
    '=',
    '=',
    '=            l',
    '=',
    '=',
    '=',
    '=            $',
    '=            l',
    '=',
    '=',
    '=',
    '=',
    '=',
    '=            l',
    '=',
    '=',
    '=',
    '=                        $             $      $    }  $           $           $    $ }          $        $           ',
    '=      }  l^^^^^^^^^^^^llllll^^^^^^^llllllllllllllllllllll^^^^^^^^ll^^^^^^llllllllllllll^^^^^^^^ll^^^^^^^ll^^^^^^^llO',
    '================================================================================================================',
    '                                                             ',
    '                                                             ',
    '                                                             ',
    '                                                             ',
'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',

  ],
  //Da brick wall
  [
    "===                                          =  =  =    O",
    "===                               $   ==l",
    "===                                l      ",
    "===            $}                  =      ",
    "===            ==            $  l         ",
    "===                     $    =            ",
    "===                   llll                ",
    "===          $                            ",
    "=======     ==                            ",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Leap O' Faith
  [
    "==========================================================================================================================",
    "=                  ^^^^^^^^^                                  ",
    "=                                                                                     } ",
    "=                                                                                ============",
    "=                   l                        }   ===           ===^^            ^^^^^^^^^^",
    "=                                            ==        ll                                        ",
    "=                                         l                                 =                    =",
    "=        =                                                                $                                    !",
    "=                 =                                                       ===",
    "= }  $$             ======           lll",
    "========                                                                                                       O",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //Descending Tomfoolery
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=     $    $         $         $     }",
    "=     =    =         =         =     =",
    "^^==^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^=",
    "        ",
    "                                     !",
    "                                      ",
    "                    !       =        $",
    "                               ^^^^",
    "                               ====  =",
    "                    $             ^  ^",
    "                               ",
    "                                     ",
    "                    $              ==",
    "                 ",
    "                    =         ^^^^^^^^^^^^^^^^^",
    "",
    "                                     ",
    "                ^^^ ! ^^^     l    l",
    "",
    "                                       O",
    "                    =                   ",
    "                          =      =    =",
    "",
    "",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Now this is hard
  [
    "=",
    "=",
    "=",
    "=                                                                                                   O",
    "=                             ",
    "=                             ",
    "=                             ",
    "=                               $    =^^                                                       =",
    "=                               =^^^^",
    "=                             ",
    "=                          =^^             l     $   ",
    "=                                              ^^==^^                                        ll",
    "=                             ",
    "=                                                           } ",
    "=                                                        ======            }  $",
    "=                                                             ^^^^^^^^^^^======  ",
    "=   }  $               $                                                      ^^^^^^^^^^^====ll",
    "==========           lll                                   ",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  ],
  //DON'T GET SPIKED
  [
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                                                                                ",
    "=                             ",
    "=                             ",
    "=                             ",
    "=                  }                                            $           ",
    "=                 ===            $     $                  $      ",
    "=                              ==========                 == ",
    "=        l   $$          ",
    "=        $                                        !",
    "=           ^^^^^^            ",
    "=                                                 l                    $",
    "=",
    "=",
    "=       l $                                         $                  O",
    "===============                                   l                   ===",
    'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  



  ],
  //Platform Chaos
  [
    '=         ^             ^^',
    '=         =             ==',
    '=         =             ==                              =',
    '=         =         k- ^==^                             =',
    '=       $ =      $ =========              !             =',
    '=        ^=             $         ^                     =',
    '=        ==             $         =                     =',
    '=                                 =                     =',
    '=                       =   l     =                     =',
    '=                                 =                    =',
    '=                   lll^          =                     =',
    '=                   =====         =                     =',
    '=                   D $$=         =                     =',
    '=                   D $$=         =       !             =',
    '=                  ======lll      =                     =',
    '=                                 =                     =',
    '=                                 =                     =',
    '=                                 =              O      =',
    '=                   ===           =                     =',
    '= } ^^^^^^^=^^^^^^^^^^^^^^^^^^^^^^=^^^^^   }            =',
    '=========================================================',

  ],
  //Enter the Secret Lair
  [
    "=                                                                          O ",
    "=                             ",
    "=                                                              $  ",
    "=                                                             ===",
    "=                                                                               ",
    "=                      ",
    "=                  $              ",
    "=                             $   -   k                    l",
    "=                                ====         $  }         $",
    "= $  $   $    }                                =====",
    "================                                           = ",
    "=              D        }",
    "=  $     $ }   D        l",
    "================    ",
    "=",    
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
  //Secret Lair
  [
    "=iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    "=",
    "=",
    "=",
    "=",
    "=                                                 ",
    "=                                                            D",
    "=                                                            D",
    "=                                                            D",
    "=                                                            D",
    "=                     }                $             $       D",
    "=         ^^^^^^^     ======^^^^====^^====^^^^====^^====^^====",
    "=                    ==                                       =",
    "=                   ==                                        =",
    "=                                                             =",
    "=   lll $llllll               $             $               DDD=",
    "=                  }   llllll===lllll=lllll===llllll=lllll=lDOD=",
    "=                  ===========================================D",
    "=          ",
    "=          =          $                    $                ",
    "=                    }",
    "=                DDD===        $           =              =  ",
    "=                D    ==^^=^^^^^^^=^^^^^^^^^^^^^^^^^^=^^^^^^^",
    "======^^^^^^^^^^^      =========================================",
    "                   l   iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii^^",
    "                   k",
    "                                                            ",
    "                                                                  =",
    "                                                            ",
    "                                                            ",
    "                      =      =^^^lllll==llllll=^^^^^^^^====        ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  

  ],
  //Rollercoaster
  [
    "=iiiiiiiiiiiii             =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=                          =",
    "=        ^                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",             
    "=  $  =  =                 =",
    "=     =  =                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=  $  =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",             
    "=     =  =                 =",
    "=     =  =                 =",
    "=  $  = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=   $ = $=                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=     =  =                 =",
    "= $   = l=>>>>>>>>>>>>>>>  =",
    "=     =  =                 =",
    "=     =  =                 =",
    "=     = l=  <<<<<<<<<<<<<<<=",
    "=     =  =                 =",
    "=   <<=  =                 =",             
    "=  ==== l=  <<<<<<<<<<<<<<<=",
    "=     = $=                 =",             
    "=     =  =                 =",
    "=     = l=>>>>>>>>>>>>>>>  =",
    "=        =                 =",             
    "=        =                 =",
    "=>>>>>>>l=OOOOOOOOOOOOOOOOO=",
    "============================",
  ],
  //Onion's got HOPS
  [
    
    "=",
    "=                                                         O                        ",
    "=                                                                     {",
    "=                                                                     =",        
    "=",
    "=",
    "=                                   $                                        {",
    "=                                                                            l",
    "=   }        $",
    "=^=^=^=^=^^^^                                                           $",
    "=                    !          =^^^^^^^^^  ^^^^^^^^^^^^^^^^^",
    "=                           ^^==                         =                 $",
    "=                      $                                  $                ",
    "=          ^^^^^^^^^^^^=                                                    l",
    "=                                          $$$}                     $",
    "=                                         =====          l  ====^^^^^^^^^^",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Cruisin' for a Bruisin'
  [
    
    "= ",
    "=",
    "=",
    "=",
    "=",
    "=                                     $ l  ",
    "=      =^^^^^^^^^^                    =                !",
    "=     =                     ^",
    "=    =",
    "=    =",
    "=   =",
    "=   =                       l",
    "= ! = $  }",
    "=   =    ===",
    "=   =         =             ",
    "=                          l",
    "=",
    "=                     -",
    "=                     l  ^",
    "=",
    "=",
    "=                         l",
    "=",
    "=",
    "=                          ^   l",
    "=",
    "=                            l",
    "=",
    "=                          $  ",
    "=",
    "=$         $               l",
    "=     $",
    "=              $",
    "=   $    $           $                               OOOOO",
    "========================iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii=====iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Mount Scallion
  [
    "=                                                                                                 =   =^^^^^^^^^$",
    "=                                                                                                =               =  =^^^",
    "=                                                                                                                      =^",
    "=                                                                                               ^^^^^=                  =^",
    "=                                                                                             =                          =^",
    "=                                                                                           ^=        ^^^^^^^      =^     =^",
    "=                                                                                          ^=                              =^",
    "=                                                                                          =                                =^",
    "=                                                                                         =                  $-$             =^",
    "=                                                                                         ^                  ===              =^",
    "=                                                                                         ^ ^^^^^^^==      ^^   ^^ !      ==   =^",
    "=                                                                                         ^                                     =^",
    "=                                                                                         ^                                      =^",
    "=                                                                                        $^         l                 ^^=         =^",
    "=                                                                                        l^        $     $    $                    =^",
    "=                                                                                         ^     ====================                =^^^^^^^^^",
    "=                                                                                         ^",
    "=                                                     ^^^^^^^^^^^^                  $^^^^^^                          O",
    "=                                                     ============           ^^^^^^^=",
    "=                                                     ^^^^^^^^^^^^          =",
    "=                                                                       ^  ^",
    "=                      $                               $$         $",
    "=                      =                              =========  ==",
    "=                      ^                              ^",
    "=                      ^                              ^",
    "=                      ^                              ^           }      l^^^^^^^^^^^^^^^^^^^^^^^^",
    "=                     ^                              ^       ^^^^==",
    "=                     ^                              ^",
    "=          $     $    ^             $$$$$$$          ^",
    "========^^^^^^^^^^l   ^            =========      l",
    "",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //DROP
  [
    "=",
    "=",
    "=                    $",
    "=               $",
    "=",
    "=",
    "= =  =  =       =    =",
    "=                                               k",
    "=                                           ^^    ^^",
    "=     =                                     ^      ^",
    "=$     }          $                         ^   = ^^",
    "=========^^^^^^^^                      l",
    "=                                             $$ }",
    "=                   }                       ====== ",
    "=               =====",
    "=                                $      =                {",
    "=                     ^^^^^^^^^^^=^^^^^^^^^^^            = ",
    "=                         ",
    "=",
    "=",
    "=                                                $ ",
    "=                                                 }",
    "=                                              =  =  ",
    "=                                               ^^",
    "=",
    "=",
    "=                            ",
    "=                                  ^             }    $       ^       }",
    "=                            =  =     =     =    =    =     =   =     =   =   =  =  =",
    "=                                                                                =  =",
    "=                                                                                =$ =   ",
    "=                                                                                =  =",
    "=                                                                                =  =",
    "=                                                                               DDDDDD",
    "=              ",
    "=                                                                                 O ",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Tower of Pain
  [
    "=",
    "=",
    "=    ^                    $$                            k",
    "=    = }       ^^^===  ^^^^^^^^     }                  ===",
    "=    ===       ======================",
    "=    =         =                   D",
    "=    =         =  !                D         }",
    "=    =    ^    =                   D      llll",            
    "=    ======    =      ^  ^         D",
    "=    $$=      ^=     llllllllll=======",
    "=      =     ===               =",
    "=      =       =             O =",
    "=      =  ^  ^ =            ====",
    "=      =  llll =======         =",
    "=      =       =               =",
    "=      =       =             $$=",
    "=      =       =^^^^^^^^^^^^====",
    "=      =       =================",
    "=      =    ^===               =",
    "=      =    ==                 =",
    "=                              =",
    "=    }                     $$$ =",
    "================           ===",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Tricky timing
  [
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=                                      ",
    "=     }                                     ",
    "==========D               =                      ",
    "=$$$$$$$$$D                            ",
    "=$$$$$$$$$D                                 ",
    "==========D                                     ",
    "=  ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^    }          ",
    "=                     ll           ==             !",
    "=           =                          ",
    "=            $                 $       ",
    "=                             ==      ",
    "=           k                                   DDDDD",
    "=           l         =                         D O D",
    "=                                               D = D",
    "iiiiiiiiiiiiii^^==^^iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Insane Precision
  [
    "", //don't make this easier
    "                          ^^   ^^^",
    "=                           $",
    "=",
    "=                        D",
    "=                        D   k  ",
    "=                        D",
    "=                     !  D",
    "=                        D     l",
    "=                        D     $",
    "=                     D  D ^^^   ^^^^^",
    "=$ }           ^     DOD       ", 
    "=====^^^^^^^^  =^^^^^===",
    "              $                l",
    "                        $",
    "                        =",
    "               }",
    "               ==",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //It's Not That Simple
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=                   ",
    "=",
    "=",
    "=                                                                     k",
    "=",
    "=            }                                      $",
    "=      $   =====                              ^     l                ^",
    "=          =   =",
    "=          i O =            $                            =",
    "= $        i   =^^^^^^^^^^^^=^^^^^^^^^^  ^^^^                       }", 
    "================                D      $       l                    l",
    "           =                    D",
    "           = O                  D",
    "           =================    =   ==^==     ===              =",
    "",
    "",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    ],
  //It's a long Drop
  [
  "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=", "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=", "=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=","=",
    
    "=                                         ^^",//haha its a long fall
    "=                               l        ====",
    "=                       ^                                               O",
    "=                       ==                               ====           =",
    "==========       ^^  ^^^    ",
    "",
    "                      }",
    "                    ===   =",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  //Into the Abyss
  [
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=        =",
    "=   -    =",
    "=  ===  = ",
    "=$  =$  =",
    "= ! =$! =",
    "=  $=$  =",
    "= $ =$  =",
    "=$  =$  =",
    "= $ =$  =",
    "=  $=$  =",
    "= $ =$  =",
    "=^  =$  =",
    "=$  =$  =",
    "=$  =$  =",
    "=$  =$  =",
    "=^  =$  =",
    "=$  =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =$  =",
    "=   =   =",
    "=   =$  =",
    "=   = $ =",
    "=   =  $=",
    "=   =  $=",
    "=   =$  =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =  $=",
    "=   = $ =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   =$  =",
    "=   = $ =",
    "=   =$  =",
    "=   =  $=",
    "=   = $ =",
    "=   = $ =",
    "=   =$  =",
    "=   = $ =",
    "=   =^^^=",
    "=^O^=^O^=",
    "=========",
    
    
  ],
  //Enter the labyrinth
  [
    "=   ===================================================================================================",
    "=                                                                                                     =",
    "=   =                                                                                                 =",
    "=   =                                                                                                 =",
    "=   =                                                      $                                        k =",
    "=   =                                                                                              ====",
    "=   =                                                      ============================================",
    "=   =                                                      =                                          =",
    "=   =                                                      =                                          =",
    "=   =                                                      =                                          =",
    "=   =                                                      =                                        O =",
    "=   =                                                      =                         $             ====",
    "=                                                          =     =                 =========^^^^^^^^^^^",//hardest
    "=   =                                                      =     =                     =", //possible
    "=   ===============================================        =     =                     =",//jump :)
    "=   ^                              =              =        =  $  =                     =",
    "=                    }   ^         =       ^^^^^  ===================                  =",
    "=                $   =   =         =       =====                    =         l        =",
    "=                ^   =          =  $  ^                             =^^^^^^^^^=        =",
    "=                =   =          =     =                             ==============l    =",
    "=      ^^^^^^^   =   =^^^=^^^^^^=  lll=^  }   ^^       ^  ^         =            $     =",
    "=ll===============================================llllllllllllll==                     =",
    "                                                               =                       =",
    "                                                               =   }         ===       =",
    "                                                               ======^^^^^^^^^^^^^^^^^^=",
    "                                                                    ====================",
    "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    
  ],
  //The Labyrinth
  [
  "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  "i                                                           i",
  "i                                                           i",
  "i                                                           i",
  "i                                                           i",
  "===========================  ================================",
  "=     =                 =                 =        =     =  =",//MAZE TIME! you can jump infinitely in this level,
  "=     =                 =           -   $ =        =     =  =",//someone do that or I will when im done
  "=        =============  ==========  =  ====  =  =  =  =  =  =",
  "=  =     =        =  =           =  =  =     =  =     =     =",
  "=  =     =        =  =           =  =  =     =  =     =     =",
  "=  =  ====  ====  =  ==========  =  ====  ====  ==========  =",
  "=  =  =        =  =        =  =  =  =     =  =  =     =     =",
  "=  =  =        =  =        =  =  =  =     =  =  =     =     =",
  "=  ====  =======  ====  =  =  =  =  =  ====  =  =  =  ====  =",
  "=     =  =  =     =     =     =  =  =  =     =  =  =     =  =",
  "=     =  =  =     =     =     =  =  =  =     =  =  =     =  =",
  "====  =  =  =  ====  ==========  =  =  =  ====  =  ====  =  =",
  "=     =     =  =     =           =     =  =     =     =  =  =",
  "=     =     =  =     =           =     =  =     =     =  =  =",
  "=  ====  ====  =  =  =  ==========  ====  =  ====  ====  =  =",
  "=        =     =  =        =     =        =        =     =  =",
  "=        =     =  =        =     =        =        =     =  =",
  "=  =======  =============  =  =  ==========  =======  ====  =",
  "=  =        =     =     =     =           =  =     =     =  =",
  "=  =        =     =     =     =   G       =  =     =     =  =",
  "=  =  ====  =  =  =  =  ================  ====  =  ====  =  =",
  "=  =  =     =  =     =     =        =           =        =  =",
  "=  =  =     =  =     =     =        =           =        =$$=",
  "=  =  ====  =  ==========  ====  =  =  ======================",
  "=  =     =  =  =        =     =  =  =  =  =           =     =",
  "=  =     =  =  =        =     =  =  =  =  =           =     =",
  "=  ====  ====  =  ====  ====  =  ====  =  =  =======  =  =  =",
  "=     =     =  =  =        =  =  =     =  =     =  =     =  =",
  "=     =     =  =  =        =  =  =     =  =     =  =     =  =",
  "====  ====  =  ====  ====  =  =  =  ====  ====  =  =======  =",
  "=  =     =  =        =     =  =        =     =        =     =",
  "=  =     =  =        =     =  =        =     =        =     =",
  "=  ====  =  ==========  ====  =======  =  =  =======  =  ====",
  "=     =  =  =        =     =     =  =  =  =     =     =     =",
  "=     =  =  =        =     =     =  =  =  =   G =     =     =",
  "=  =  =  =  =  =  =======  ====  =  =  ====  ====  =======  =",
  "=  =     =  =  =  =        =     =  =  =     =     =        =",
  "=  =     =  =  =  =        =     =  =  =     =     =        =",
  "=  =======  =  =  =  =======  ====  =  =  ====  ====  ====  =",
  "=  =     =     =     =  =     =     =  =     =  =  =  =  =  =",
  "=  =     =     =     =  =     =     =  =     =  =  =  =  =  =",
  "=  ====  =============  =  =======  =  ====  =  =  =  =  =  =",
  "=              =        =  =     =        =  =     =  =     =",
  "=        G     =        =  =     =        =  =     =  =     =",
  "=============  ====  =  =  =  =  =======  =  ====  =  =  ====",
  "=  =                 =  =     =     =        =     =  =  =  =",
  "=  =                 =  =     =     =        =     =  =  =  =",
  "=  =  ============================  ==========  ====  =  =  =",
  "=     =  =              =        =              =  =  =     =",
  "=     =  =              =        =              =  =  =     =",
  "=  ====  =  ==========  =  ====  =  =============  =  ====  =",
  "=        =           =     =  =  =                 =  =     =",
  "=        =           =     =  =  =                 =  =     =",
  "=======  ==========  =======  =  ===================  =======",
  "=     =           =  =     =                       =        =",
  "=     =           =  =     =             G         =        =",
  "=  =============  =  =  =  ======================  =======  =",
  "=                 =     =        =                          =",
  "=             k   =     =        =                          =",
  "=============================DDD============================",
  "                              ",
  "                              O  ",
  "",
  "",
  "iiiiiiiiiiiiiiiiiiiiiiiiiiiii i iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
  //Onion's Demise
  [
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=",
    "=                       ^^^    O",
    "=                ===============",
    "=                = = = = = = = =",
    "=                ===============",
    "=                = = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "=               l===============",
    "=               l= = = = = = = =",
    "================================iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  ],
  // the heist (made is level designer)
[
  '=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                   =     =                                     ',
'=                   =G   G=                                     ',
'=                   =DDDDD=                                     ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                                                               ',
'=                    D$$D        ^                              ',
'=                    D$$D        ^                              ',
'=            $       D$$D        ^                              ',
'=                    D$$D        ^                              ',
'=                    DDDD        ^                              ',
'=                                ^                              ',
'=                               O^                              ',
'=      $     l     =  Gk   =     ^                              ',
'============= ====^==============^                              ',
'                                                                ',
],

	//We're Just Getting Started
[
	"     =",
	"     =",
	"     ============================================================",
	"       =                                         =     =        =",
	"       =                                         =     =        =",
	"                        ===     ^  ===   ===  ^                 =",
	"                  ^^    = ===   ====          =     ^     ^     =",
	"          ^  ^    ==    =       =             =     =     =     =",
	"     ^  llllllll  ==    =^^^^^^^=^^^^^^^^^^^^^=  ^  =  ^  =     =",
	"===============================================lllllllllllll OO =",
],
	[
	"=    ================================",
	"=    =                     =  =      ",
	"=    =    k                =  =      ",
	"=    =   =========  v      =O        ",
	"=    =   vv                =         ",
	"=    =                     =         ",
	"=    =                     =^^^^^^   ",
	"=    =              l      ========  ",
	"=    =   ^                 D         ",
	"=    =   =ll=              D         ",
	"=                          ========  ",
	"=                          =         ",
	"=        ^^^^^^^^^^^^^^^^^^=^^^^^^^^^",
	"=====================================",
		],
	[
"=   = O             =",
"=   =               =",
"=   =====           =",
"=   = k =           =",
"=   =   =       D   =",
"=   =   =       D   =",
"=   =   =       =====",
"=   ==  =           =",
"=   =               =",
"=   =               =",
"=   ========        =",
"=   =               =",
"=   =               =",
"=   =              ==",
"=                  ==",
"=                ^^==",
"=====================",
		],
	[
"===========   OO   =",
"=         =   vv   =",
"=         =        =",
"=    ^^  ^=        =",
"=======  ==        =",
"=    $=  D=^^^     =",
"=    $=  D====ll   =",
"=   ===  D         =",
"=        D         =",
"=        D         =",
"=k  ^^^  D  ^^  ^^^=",
"====================",

		],
	[
"=  =            ^  ^^^  ^^^^^  ^^",
"=  =            =============  ==",
"=  =            =               =",
"=  =     =      =               =",
"=  =            =   ^^          =",
"=  =            =  =ll===       =",
"=  =            =       =       =",
"=  =         =  =       =       =",
"=  =vv=      =  =   ^^  =^^  iii=",
"=  =     =============  ==========",
"=  =     =",
"=  =     =            OO",
"=  =lll===",
"=  =     =",
"=  =     =",
"=      = =",
"=      = =",
"==========",


		],
	//Freaky Deeky
	//Eli, if you even touch this level, I will doxx you and your family, call up my uncle and tell him to barrage you with so many scam calls that you will never have a moment of peace ever again. Comprende amigo?
[
"i    G                    iiiiii                                                   i",
"i                                                                                  i",
"i^      ^        h                                                                  i",
"i========  ^^== ===??===    ==  === = ===????===   =^=^==   =====   = =  ====  i",
"i   v  v               hh  ll                i i                                  i",
"i                        ?                                                         i",
"i                                                                                  i",
"i                                                                                  i",
"i      ==??==      hh    ==l====       =====??                                i",
"i        ii        ll                      ^^                                        i",
"i                                                                                  i",
"i                            ^       G^                                             i",
"i   ==?===    i==??===   i   =====i====iiii   =i====  l ==?== ? l ===l ===  ====   i",
"i       i                                                                         i",
"i                                                                                  i",
"i                                                                                  i",
"i                                                                                  i",
"iii????hh      ii??i       ii?===h?ii         ii===h=ii      i???ii         ii??ii",
"i                                                                                  i",
"$   =====                              ^     l                ^                    i",
"=          =   =                                                                   i",
"=          i  =            $                            =                          i",
"=hh       i   =iiiiiiiiiiii=iiiiiiiii^  iii^                                       i", 
"                                                                                   i",
"     ==?==                h      $       l                    l                    i",
"                                                                                   i",
"i                                                                                  i",
"i ^         =     h               h                                                i",
"i                                                                                  i",
"           =             h      h                                                  i",
"i                                                                                  i",
"           ===??===h=======    =   ==^==     ===              =                    i",                             
"i                                                                                  i",
"i  ==??=  =h=  == ==??==   =?=  ==?=^     ^==??= ==i  ===   == ==??==   ==??=    = i",
"",
"====  =  ====  ====    ====  =  =  =======  = i  ==                                i",
"",
"",
  "=     ?     ?  =  =        i  =  ?     ?  =     =  h     =  =                     i",
"",
"",
  "?     =     i  =  ? h      ?  =  i     h  =     ?  =     =  =                     i",
"",
"",
  "====  ====  =  ==h===  =  =  =  ====  ====  ?  ===h===  =                     i",
"",
  "=  =     =  =        =     i  =            i                                     i",
"                                                                                    i",
"i   ==i??==  =??=====  ??  ===== ^ = ^ =  =  ==??==   ===== ====  ==i==  ===??===ii i",
"",
"                        ===     ^  ===   ===  ^                 =",
"",
"",
	"                  ^^    = ===   ====          =     h     i     =",
"",
"",
	"          ^  ^    ==    =       =             ?     =     =     =",
"",
"",
"        ^   G   ^                                                    iiiiiiiiiiii===i ",
"i       ===hh===  ====        ==??=        =??==        ===                         i",
"                                                                                    O",
"i    ^     l    iii^llllliii ^ ^^l^ ^ ^ l ^ l ^ l ^     ^ h ^                            i",
"i                                                                                 h      i",
"i                                                                                  iiiiiii",
"i                      v      l                                                    i",
"i                  ^v^v^v^v^v           G                    v   v                 i",
"i====   ==  i===i =  ==  =  =  ===  ^=======^ == ^ ??  ?=  ==  =  =  =??==  =  h   i",
"i     l                           l             l  ==          l         l         i",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
],
	//dodging and weaving
[
"=              =",
"=              =",
"=              =",
"=              =",
"=  $$$$        =",	
"=              =",
"===========    =",
"          =  ^^=",
"          =    =",
"          = $$ =",
"          =    =",
"          =^^  =",
"          =    =",
"          = $$ =",
"          =   l=",
"          =    =",
"          =    =",
"          =^$$^=",
"          =^$$^=",
"          =^$$^=",
"          =OOOO=",
"          =====",
],
	 [
"", //The Tube
"",
"       iiiiiiiiiiiiiii^",
"===    ================   =        =",
"  =                       =        =",
"  ==                      =iii  iii=",
"       ===    ===    ==   =        =",
"                          =        =",
"                          =        =",
"                          =        =",
"                          = iii    =",
"                          =^===  ^^=",
"                          =        =",
"                          =        =",
"                          =  ^^    =",
"                          =  =======",
"                          =        =",
"                          =        =",
"                          =    ^^  =",
"                          =======  =",
"===========================     =  =",
"=           =                   =  =",
"=           =                      =",
"=  ^^  ^^   =  ^     ====   =      =",
"=  =======  =  =        =   =      =",
"=        =     =        =   =     ==",
"=        =     =        =   =     ==",
"=        =     =iiiiii^^=iii=iii^^==",
"=^       =lllll=====================",
"=======  =",
"=        =",
"=        =",
"=    ^^  =",
"=  =======",
"=        =                                            iiiiiiiiii",
"=        =                                            i        i",
"=        =                                            i   OO   i",
"=        ==============================================DDDDDDDD=",
"=        =             =       =             =                 =",
"=        =             =       =             =                 =",
"=        =             =       =       ====  =   ====          =",
"=^^  iii^=             =========       =     =   =             =",
"=            =======                  ==     =  ==           ===",
"=            = $$$ =                  =   ====  =              =",
"=            =                        =         =              =",
"=          ^^=          ^^   ^^       =         =              =",
"==============llllllllllllllllll=======================        =",
"                                                      =iii     =",
"                                                      =====    =",
"                                                      =        =",
"                                                      =        =",
"                                                      =        =",
"                                                      =       ==",
"                                                      =       ==",
"                                                      =        =",
"                                                      =iii     =",
"                                                      =vvv=    =",
"                                                      =        =",
"                                                      =        =",
"                                                      =        =",
"                                                      =      ===",
"                                                      =  ^  ^  =",
"                                                      =  =ll=  =",
"                                                      =        =",
"                                                      =      k =",
"                                                      =        =",
"                                                      ==========",




		 ],
	 //Electric Boogaloo
	 [
"=                   =",
"=                 ^ =",
"=               ^   =",
"=                   =",
"=                   =",
"==========          =",
"=           ^^   l  =",
"=                   =",
"=                   =",
"=vvvvv             l=",
"=                   =",
"=                   =",
"=   =====           =",
"=                   =",
"=                   =",
"=k  vvvvv           =",
"=             l     =",
"=                   =",
"=ll===              =",
"=          ll  ^    =",
"=                   =",
"=                   =",
"=                   =",
"=                   =",
"=                   =",
"=   ======^         =",
"=                   =",
"=         l===^^    =",
"=                   =",
"=l^^===========     =",
"=                   =",
"=                   =",
"=                   =",
"=       ^^^^^^^^^^^^=",
"=                   =",
"======              =",
"=    ^              =",
"=    iiiiii   iiiiii=",
"=    ^              =",
"=       =============",
"=                   =",
"=                   =",
"=          =  ^  ^  =",
"=          =  =ll=  =",
"=          =        =",
"=          DDDDDDDDDD",
"=          =        =",
"=          =        =",
"=          =        =",
"          ^^^^ O ^^^^",
	 ],
	 [ //WAGHAHAHGHAHAGAGHAGHAHHHGHHHH
	 ' k=                                                             ',
'DD=                                                      = =DD= ',
'  =  D                                   D          =      =  = ',
'  =             D          D                               =OO= ',
'  =                                            D           ==== ',
'  =                   D             D                           ',
'  =D                                                   =        ',
'  =                                              D              ',
'  =           D                                                 ',
'  =                                D  D                         ',
'  =                  D       D                   D      =       ',
'  =   D                                                         ',
'  =                                                             ',
'  =                                                         D   ',
'  =          D         D                             =          ',
'  =                                           D                 ',
'  =                             D     D                         ',
'  =                                                     =       ',
'  =                                                             ',
'  =              D      D                                       ',
'  =         D                                                   ',
'  =                                     D                  =    ',
'  =     D                                                       ',
'  =                                                  =          ',
'  =D                                                            ',
'  =          D         D                                        ',
'  =                                  =        =       D         ',
'  =                                                             ',
'  =                           =                                 ',
'  =                                             D               ',
'  =   D                D                                        ',
'  =          D                                                  ',
'  =                               =                           D ',
'  =                                                             ',
'  =                                                             ',
'  =                             =                               ',
'  =  D        =                                                 ',
'                    =                                           ',
'                            =              D          D         ',
'                                                 D            D ',
'         =                                                      ',
'==                                                              ',
	 ],
//ChatGPT Generated level
	  [
    "=     =vvvvvvvvvvvvvvvvDO ============",
    "=     =                DD=            ",
    "=     =   ^   ==  ^^     =            ",
    "=     =                               ",
    "=                                     =",
    "=     ===========    ====             ",
    "=     =              =                ",
    "=     =        ^     =               =",
    "=      ^^^^^  =====  =               =",
    "=      =    =====>   =                ",
    "=      =             =              ==",
    "=      =             =                ",
    "=      =         ^^===                ",
    "=      =     ===========             ",
    "=      =^^   =          =            ",
    "=      ==    =          =            ",
    "=     <     ==^^^       =            ",
    "=           =========== =            ",
    "=          <        = =              ",
    "=      l         =^^^== =      k     ",
    "<<<>>>><><<<<>>><<llllllllllllllllll ",
],
	 [
    "=       ========= O =================",
    "=       =        =DD                =",
    "=       =        =                  =",
    "=       =        =                  =",
    "=       =  ^     =    ^   ^  ^      =",
    "=       ====  >====  === === ===    =",
    "=            =     ==         =     =",
    "=            =        ^^^^    =     =",
    "=       ^   ==        ====  k =     =",
    "=      ===     ^     =        =     =",
    "=       =      =  <===        =     =",
    "=       =      =    ==        =     =",
    "=       =^^^   =    ==   ^^^  =     =",
    "=     l====    =    ==  ====  =     =",
    "=======        =    ==         =    =",
    "=              =    =          =    =",
    "=          ^   =  ^^=^^    ^   =    =",
    "=     === =============  ======    =",
    "=                                    ",
    "================llllllllllllllllll===",
],
	  [
    "=    ^^      ========= O ==================",
    "=    ==      =        =DD                =",
    "=    ^^      =        =                  =",
    "=    ==      =        =                  =",
    "=    ==      =  ^     =    ^   ^  ^      =",
    "=    ==  >====  ===  ==== ==  === ===    =",
    "=        =     ==        ^      =        =",
    "=  ^^^   =        ^^^^    =      =       =",
    "=  ====  =^^<==^^====^^  =   ==  =       =",
    "=        =^^  k  =^^     =       =       =",
    "=  <==>  ===     =  <=== =  ===  =       =",
    "=        =^^     =  ^^   =       =       =",
    "=        ====    =  ===  =    ^^^=       =",
    "=  l     =       =       =   =====       =",
    "======>  =      ==    ^^^=       =       =",
    "=        =       =    ===       ^=^      =",
    "=        =   ^   =  ^^=^^^  ^   = =       =",
    "=   ==== =  ===  ========  ===  = =       =",
    "=        =                   =    =       =",
    "=    ^^^ =    ^         ^^^  =    =       =",
    "=   ==== =   ===  ==^  ^===  =  ===       =",
    "=                  l                      =",
    "=================llllllllllllllllll=======",
],
	 [
    "=                ========= O ==================",
    "=   ^^^          =        =DD                 =",
    "=   ===          =        =                  =",
    "=                =        =                  =",
    "=        ^  ^^   =  ^     =    ^   ^  ^      =",
    "=    ==  =  >====  ===  =     == === ===    =",
    "=  ^    =     ==  ^     ^      =        =  =",
    "=  ^^^  =     ^  ^^^^    =  ^   =       =  =",
    "=  ==== =^^<  ^^====^^  =   ==  =       =  =",
    "=  ^            =^^     =       =   ^^  =  =",
    "=  <==>         =  <=   =  ===  =   ==  =  =",
    "=  ^^    =^^    =  ^^   =       =  l    =  =",
    "=  ==    ========  ===  =   ^^^^=  ====>=  =",
    "=  l      =  k          =   =====       =  =",
    "=^====>   =          ==^=       =  ^^   =  =",
    "=   ^^^   =       =    ===      ^ =  ===   =",
    "=    ^   =   ^   =  ^^=^^^  ^   = =        =",
    "=   ===  =  ===  ========  ===  = =    ^^^ =",
    "=        =                   =    =  ===== =",
    "=        =    ^   ^^^   ^^^  =    =        =",
    "=   ==== =   ===  ===  ====  ======  ^^    =",
    "=         =              l        =   ==   =",
    "=     ^^^^^=                  =        <   =",
    "====     =======llllllllllllllllll======^^^=",
    "=                     =                   ==",
    "=  l  l                                     =",
    "=        ==========                         =",
    "= ^^=====                                   =",
    "=============================================",
],

 [
    "=   =l  ^  O ============================",
    "=   ==    =DDD    ^^             =   ==",
    "=   ==    =                      =  ==",
    "=     =   ==  ==          l ==    == =",
    "=   ==    =   = ========^^  ==   l == ==",
    "=    =    ==     ==     l     =    == =",
    "=   l==    ==   == l     ==   l =    ==",
    "=   =    ==  ^^  ==     ==   =     ==",
    "=   =    ==  ^^   ==     ==  =     == ",
    "=   ==   ==     ==      l ==    == ==",
    "=                                   =",
    "=    ==     l  ==    ==  ==    ==    =",
    "=                                   =",
    "=    ==    ==  ==     ==   ==    =  =",
    "=   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   =",
    "=  ^=============================   =",
    "=    ==         ==      ==   ==    ==",
    "=    ==         ==       ==          =",
    "=    ==   ==    ==  ==     ==    == =",
    "=^  ==    ==   ==    ==   ==    ==  =",
    "=    ==    ==  ==  k  ==   ==       =",
    "=  ^==    ==    ==   ==    ==       =",
    "=    ==   ==     ==    ==    ==    ==",
    "=         ==    ==   ==    ==    ==  =",
    "=          ==          ==          == =",
    "=  ^==    ==          ==          == =",
    "======================================="
],[
"=                                              =",
"=                                              =",
"=                                              =",
"=                                              =",
"=                                              =",
"=                                              =",
"=                                              =",
"=                                              =",
"=                                            O =",
"=                                              =",
"=                                              =",
"=      =G =          =G =          =G =    =  G=",
"===     ==            ==            ==      ====",
"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
]






  //end of level code 
]

const levelConf = {
  tileWidth: 64,
  tileHeight: 64,

  tiles:{
    "=": () => [
      sprite("grass"),
      area(),
      body({ isStatic: true }),
      scale(1),
      offscreen({ hide: true }),
      anchor("bot"),
      "ground"
    ],
    "+": () => [
      sprite("grass5"),
      area(new Rect(vec2(), 160, 32)),
      body({ isStatic: true }),
      offscreen({ hide: true, distance: 160 }),
      scale(1),
      anchor("bot"),
      "ground"
    ],
    "_": () => [
      sprite("grass25"),
      area(new Rect(vec2(), 800, 32)),
      body({ isStatic: true }),
      offscreen({ hide: true, distance: 800 }),
      scale(1),
      anchor("bot"),
      "ground"
    ],
    "?": () => [
      sprite("fake"),
      area(),
      scale(1),
      offscreen({ hide: true }),
      anchor("bot"),
      "ground"
    ],
    "$": () => [
      sprite("coin"),
      area(),
      offscreen({ hide: true }),
      anchor("bot"),
      "coin",
    ],
    "^": () => [
      sprite("spike"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true }),
      anchor("bot"),
      "danger",
    ],
    "`": () => [
      sprite("spike3"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true, distance: 96 }),
      anchor("bot"),
      "danger",
    ],
    "&": () => [
      sprite("spike9"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true, distance: 288 }),
      anchor("bot"),
      "danger",
    ],
    "v": () => [
      sprite("dspike"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true }),
      anchor("top"),
      "danger",
    ],
    "O": () => [
      sprite("portal"),
      area({ scale: 0.5, }),
      offscreen({ hide: true }),
      pos(0, -12),
      anchor("bot"),
      "portal",
    ],
    "l": () => [
      sprite("jumpy"),
      anchor("bot"),
      offscreen({ hide: true }),
      area(),
      "jumpy",
    ],
    "D": () => [
      sprite("door"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true }),
      anchor("bot"),
      "door",
    ],
    "k": () => [
      sprite("key"),
      offscreen({ hide: true }),
      area(),
      anchor("bot"),
      "key",
    ],
    ">": () => [
      sprite("coasterRight"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true }),
      anchor("bot"),
      "right",
    ],
    "<": () => [
      sprite("coasterLeft"),
      area(),
      body({ isStatic: true }),
      offscreen({ hide: true }),
      anchor("bot"),
      "left",
    ],
    ".": () => [
      sprite("block"),
      area(),
      offscreen({ hide: true }),
      body({ isStatic: true }),
      anchor("bot"),
    ],
    "{": () => [
      sprite("signpostl"),
      area(),
      offscreen({ hide: true }),
      anchor("bot"), 
    ],
      "}": () => [
      sprite("signpostr"),
      area(),
      offscreen({ hide: true }),
      anchor("bot"), 
    ],
      "-": () => [
      sprite("signposte"),
      area(),
      offscreen({ hide: true }),
      anchor("bot"), 
    ],
      "i": () => [
      sprite("invisdanger"),
      offscreen({ hide: true }),
      area(),
      "danger",
      anchor("bot"), 
    ],
    "~": () => [
      sprite("invis25"),
      area(new Rect(vec2(), 800, 32)),
      offscreen({ hide: true, distance: 1 }),
      "danger",
      anchor("bot"), 
    ],
    "#": () => [
      rect(2400, 32),
      area(new Rect(vec2(), 2400, 32)),
      offscreen({ hide: true, distance: 1 }),
      "danger",
      anchor("bot"), 
      opacity(0),
    ],
    "S": () => [
      sprite("invisdanger"),
      area(),
      offscreen({ hide: true }),
      "spawn",
      anchor("bot"), 
    ],
    "Q": () => [
      sprite("invisdanger"),
      area(),
      offscreen({ hide: true }),
      "arg",
      anchor("bot"),
    ],
    "G": () => [
      sprite("ghost"),
      patrol(),
      offscreen({ hide: true }),
      "enemy",
      anchor("bot"),
      area(), 
      body(), 
      ],
    "!": () => [
      sprite("darrow"),
      anchor("bot"),
      offscreen({ hide: true }),
      area(),
    ],
  },
  
}
function patrol(speed = 60, dir = 1) {
	return {
		id: "patrol",
		require: [ "pos", "area", ],
		add() {
			this.on("collide", (obj, col) => {
				if (col.isLeft() || col.isRight()) {
					dir = -dir
				}
			})
		},
		update() {
			this.move(speed * dir, 0)
		},
	}
}

export { LEVELS, levelConf }
