const textures = [
    ["onion", "assets/sprites/onion.png"],
    ["grass5", "assets/sprites/grass5.png"],
    ["grass25", "assets/sprites/grass25.png"],
    ["bigonion", "assets/sprites/bigonion.png"],
    ["grass", "assets/sprites/grass.png"],
    ["coin", "assets/sprites/coin.png"],
    ["portal", "assets/sprites/portal.png"],
    ["spike", "assets/sprites/spike.png"],
    ["spike3", "assets/sprites/spike3.png"],
    ["spike9", "assets/sprites/spike9.png"],
    ["dspike", "assets/sprites/dspike.png"],
    ["invisdanger", "assets/sprites/invisdanger.png"],
    ["invis25", "assets/sprites/invis25.png"],
    ["jumpy", "assets/sprites/jumpy.png"],
    ["heart", "assets/sprites/heart.png"],
    ["cloud", "assets/sprites/cloud.png"],
    ["boom", "assets/sprites/boom.png"],
    ["key", "assets/sprites/key.png"],
    ["door", "assets/sprites/door.png"],
    ["coasterLeft", "assets/sprites/coasterLeft.png"],
    ["coasterRight", "assets/sprites/coasterRight.png"],
    ["block", "assets/sprites/block.png"],
    ["lvlbtn", "assets/sprites/lvlbtn.png"],
    ["lvlSelect", "assets/sprites/lvlselect.png"],
    ["startbtn", "assets/sprites/startbtn.png"],
    ["keyboardB", "assets/sprites/keyboard_b.svg"],
    ["keyboardR", "assets/sprites/keyboard_r.svg"],
    ["arrowl", "assets/sprites/arrowl.png"],
    ["signpostl", "assets/sprites/signpostl.png"],
    ["signpostr", "assets/sprites/signpostr.png"],
    ["signposte", "assets/sprites/signposte.png"],
    ["arrowr", "assets/sprites/arrowr.png"],
    ["lockedarrowr", "assets/sprites/lockedarrowr.png"],
    ["rightmove", "assets/sprites/rightchevron.png"],
    ["leftmove", "assets/sprites/chevronleft.png"],
    ["jumpbutton", "assets/sprites/jumpbutton.png"],
    ["restart", "assets/sprites/replay.png"],
    ["home", "assets/sprites/home.png"],
    ["jumpright", "assets/sprites/jumpright.png"],
    ["jumpleft", "assets/sprites/jumpleft.png"],
    ["ghost", "assets/sprites/ghosty.png"],
    ["nopiracy", "assets/sprites/nopirates.png"],
    ["darrow", "assets/sprites/darrow.png"],
    ["fake", "assets/sprites/fake.png"],
    ["dj", "assets/sprites/dj.png"],
    ["skinsBtn", "assets/sprites/skinsBtn.png"],
    ["achBtn", "assets/sprites/achBtn.png"],
    ["onion-red", "assets/sprites/onion-watermelon.png"],
    ["onion-beach", "assets/sprites/onion-beach.png"],
    ["onion-watermelon", "assets/sprites/onion-watermelon2.png"],
    ["onion-blue", "assets/sprites/onion-blue.png"],
    ["onion-gold", "assets/sprites/onion-gold.png"],
    ["onion-dark", "assets/sprites/onion-dark.png"],
    ["achievement", "assets/sprites/trophy.png"],
    ["onion-eggplant", "assets/sprites/eggplant-onion.png"],
    ["onion-magic", "assets/sprites/magic-onion.png"],
    ["onion-pumpkin", "assets/sprites/onion-pumpkin.png"],
    ["onion-invert", "assets/sprites/onionInvert.png"],
    ["onion-ocean", "assets/sprites/onion-ocean.png"],
    ["onion-secret", "assets/sprites/onion-secret.png"],
    ["winSpin", "assets/sprites/portal1.png"],
    ["winSpinBtn", "assets/sprites/winSpinBtn.png"],
    ["lightbulb", "assets/sprites/lightbulb.png"],
    ["water", "assets/sprites/water.png"],
    ["sand", "assets/sprites/sand.png"],
    ["ghostiny", "assets/sprites/ghostiny.png"],
    ["bag", "assets/sprites/bag.png"]
];

const sounds = [
    ["death", "assets/sounds/bug.mp3"],
    ["portal", "assets/sounds/portal.mp3"],
    ["score", "assets/sounds/score.mp3"],
    ["jump", "assets/sounds/hit.mp3"],
    ["jumpy", "assets/sounds/spring.mp3"],
    ["win", "assets/sounds/error.mp3"]
];

const music = [
    ["OverworldlyFoe", "assets/sounds/music.ogg"]
];

export { textures, sounds, music };